services:
  credentials:
    image: ghcr.io/dertyp7214/synara-credentials:latest-dev
    ports:
      - "8083:8083"
    environment:
      - CREDENTIAL_SERVER_PORT=8083
      - CREDENTIAL_SERVER_ADMIN_KEY=${CREDENTIAL_SERVER_ADMIN_KEY}
      - CREDENTIAL_SERVER_MASTER_KEY=${CREDENTIAL_SERVER_MASTER_KEY}
      - CREDENTIAL_SERVER_DB_URL=jdbc:sqlite:/data/credentials.db
    volumes:
      - ./credentials-data:/data
    restart: unless-stopped
