FROM mwader/static-ffmpeg:7.1.1 AS ffmpeg-builder

FROM eclipse-temurin:25-jre AS runtime

ARG APP_USER_ID=1000
ARG APP_GROUP_ID=1000

ARG MONTH_YEAR=unknown

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libstdc++6 \
    zlib1g \
    libc6 \
    shadow-utils \
    libva-drm2 \
    libva2 \
    libdrm2 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ln -sf /usr/bin/python3.13 /usr/bin/python3

COPY --from=ffmpeg-builder /ffmpeg /usr/bin/
COPY --from=ffmpeg-builder /ffprobe /usr/bin/

ENV LD_LIBRARY_PATH="/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH"

RUN groupadd -g $APP_GROUP_ID appgroup && useradd -u $APP_USER_ID -g appgroup -s /bin/bash -m -d /home/appuser appuser

EXPOSE 8080

RUN mkdir /app && chown appuser:appgroup /app

RUN mkdir /data && chown appuser:appgroup /data

RUN mkdir /backups && chown appuser:appgroup /backups

RUN mkdir -p /home/appuser/.tiddl
RUN mkdir -p /home/appuser/.config/tidal_dl_ng
RUN chown -R appuser:appgroup /home/appuser

ARG DAY_MONTH_YEAR=unknown

RUN python3 -m pip install --break-system-packages --no-cache-dir syncedlyrics tiddl #  tidal-dl-ng

COPY --chown=appuser:appuser docker/tiddl/config.toml /home/appuser/.tiddl/config.toml
COPY --chown=appuser:appuser docker/tdn-config/settings.json /home/appuser/.config/tidal_dl_ng/settings.json
COPY --chown=appuser:appgroup *.jar /app/synara-api.jar

USER appuser

ENV AUDIO_TRACKS_PATH="/data/Tidal/Tracks"
ENV AUDIO_ALBUMS_PATH="/data/Tidal/Albums"
ENV AUDIO_PLAYLISTS_PATH="/data/Tidal/Playlists"
ENV AUDIO_TRANSCODE_PATH="/data/Tidal/Transcode"
ENV AUDIO_CUSTOM_PATH="/data/Synara/custom"
ENV DATA_IMAGES_PATH="/data/Tidal/Images"
ENV BACKUP_DIR="/backups"

ENV AUDIO_TRACKS_SECONDARY_PATH="/data/Synara"

ENV HOME=/home/appuser
ENTRYPOINT ["java","--enable-native-access=ALL-UNNAMED","-jar","/app/synara-api.jar"]