FROM mwader/static-ffmpeg:6.1.3 AS ffmpeg-builder

FROM amazoncorretto:25 AS runtime

ARG APP_USER_ID=1000
ARG APP_GROUP_ID=1000

RUN yum update -y && yum install -y python3.12 python3.12-pip libstdc++ zlib glibc shadow-utils && \
    yum clean all && rm -rf /var/cache/yum

RUN ln -sf /usr/bin/python3.12 /usr/bin/python3
RUN python3 -m pip install --break-system-packages --no-cache-dir tidal-dl-ng

COPY --from=ffmpeg-builder /ffmpeg /usr/bin/
COPY --from=ffmpeg-builder /ffprobe /usr/bin/

ENV LD_LIBRARY_PATH="/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH"

RUN groupadd -g $APP_GROUP_ID appgroup && useradd -u $APP_USER_ID -g appgroup -s /bin/bash -m -d /home/appuser appuser

EXPOSE 8080

RUN mkdir /app
RUN chown appuser:appgroup /app

RUN mkdir /data
RUN chown appuser:appgroup /data

RUN mkdir -p /home/appuser/.config/tidal_dl_ng
RUN chown -R appuser:appgroup /home/appuser

COPY --chown=appuser:appuser docker/tdn-config/settings.json /home/appuser/.config/tidal_dl_ng/settings.json
COPY --chown=appuser:appgroup *.jar /app/synara-api.jar

USER appuser

ENV AUDIO_TRACKS_PATH="/data/Tidal/Tracks"
ENV AUDIO_ALBUMS_PATH="/data/Tidal/Albums"
ENV AUDIO_PLAYLISTS_PATH="/data/Tidal/Playlists"
ENV AUDIO_TRANSCODE_PATH="/data/Tidal/Transcode"
ENV DATA_IMAGES_PATH="/data/Tidal/Images"

ENV AUDIO_TRACKS_SECONDARY_PATH="/data/Synara"

ENV TDN_TOKEN_PATH="/home/appuser/.config/tidal_dl_ng/token.json"

ENV HOME=/home/appuser
ENTRYPOINT ["java","--enable-native-access=ALL-UNNAMED","-jar","/app/synara-api.jar"]