FROM amazoncorretto:25 AS runtime
EXPOSE 8083
RUN mkdir /app /data
VOLUME /data
COPY *.jar /app/credential-server-all.jar
ENV CREDENTIAL_SERVER_PORT=8083
ENV CREDENTIAL_SERVER_DB_URL=jdbc:sqlite:/data/credentials.db
ENV CREDENTIAL_SERVER_KEY_FILE=/data/master.key
ENTRYPOINT ["java", "--enable-native-access=ALL-UNNAMED", "-jar", "/app/credential-server-all.jar"]
