services:
  api:
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    environment:
      CLIENT_ID: test-id
      CLIENT_SECRET: test-secret
      DB_DRIVER: org.postgresql.Driver
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://127.0.0.1:6432/synara-api-db
      DB_USER: postgres
      HOST_GID: '1000'
      HOST_UID: '1000'
      JWT_AUDIENCE: synara-api
      JWT_ISSUER: synara
      JWT_REALM: Access to 'Synara-API'
      JWT_SECRET: some-secret
      PORT: '8081'
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: '7379'
    image: ghcr.io/dertyp7214/synara:latest-dev
    network_mode: host
    platform: linux/amd64
    pull_policy: always
    restart: unless-stopped
    user: '1000:1000'
    volumes:
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/External/Synara
        target: /data
        type: bind
      - read_only: False
        source: config
        target: /home/appuser/.config
        type: volume

  db:
    environment:
      POSTGRES_DB: synara-api-db
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      interval: 1s
      test:
        - CMD-SHELL
        - pg_isready -U postgres
    image: postgres
    platform: linux/amd64
    ports:
      - '6432:5432'
    pull_policy: missing
    restart: unless-stopped
    user: '1000:1000'
    volumes:
      - read_only: False
        source: postgres
        target: /var/lib/postgresql
        type: volume

  redis-cache:
    command: >-
      redis-server --appendonly yes --maxmemory 4gb --maxmemory-policy
      allkeys-lfu
    healthcheck:
      interval: 1s
      test:
        - CMD-SHELL
        - redis-cli ping
    image: redis:alpine
    platform: linux/amd64
    ports:
      - '7379:6379'
    pull_policy: missing
    restart: unless-stopped
    volumes:
      - read_only: False
        source: redis_data
        target: /data
        type: volume

volumes:
  config: {}
  postgres: {}
  redis_data: {}

x-portals:
  - host: 0.0.0.0
    name: API Stats
    path: /stats
    port: 8081
    scheme: http
