ktor:
    application:
        modules:
            - dev.dertyp.ApplicationKt.module
    deployment:
        port: $PORT:8080
client:
  id: ${CLIENT_ID}
  secret: ${CLIENT_SECRET}
redis:
  host: ${REDIS_HOST:}
  port: ${REDIS_PORT:}
jwt:
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}
  realm: ${JWT_REALM}
  secret: ${JWT_SECRET}
storage:
  driverClassName: ${DB_DRIVER}
  jdbcURL: ${DB_URL}
  user: ${DB_USER:}
  password: ${DB_PASSWORD:}
audio:
  tracks: ${AUDIO_TRACKS_PATH}
  albums: ${AUDIO_ALBUMS_PATH}
  playlists: ${AUDIO_PLAYLISTS_PATH}
  transcode: ${AUDIO_TRANSCODE_PATH}
  secondary-tracks:
    - ${AUDIO_TRACKS_SECONDARY_PATH:}
data:
  images: ${DATA_IMAGES_PATH}
spotify:
  clientId: ${SPOTIFY_CLIENT_ID}
  clientSecret: ${SPOTIFY_CLIENT_SECRET}
tidal:
  clientId: ${TIDAL_CLIENT_ID}
  clientSecret: ${TIDAL_CLIENT_SECRET}
  tdnTokenPath: ${TDN_TOKEN_PATH:}