ktor:
    application:
        modules:
            - dev.dertyp.ApplicationKt.module
    deployment:
        port: ${PORT:8080}
server:
  sslSupported: ${SERVER_SSL_SUPPORTED:false}
client:
  id: ${CLIENT_ID:}
  secret: ${CLIENT_SECRET:}
backup:
  dir: ${BACKUP_DIR:}
setup:
  fromBackup: ${SETUP_FROM_BACKUP:}
  fromMirror:
    url: ${SETUP_FROM_MIRROR_URL:}
    username: ${SETUP_FROM_MIRROR_USERNAME:}
    password: ${SETUP_FROM_MIRROR_PASSWORD:}
redis:
  host: ${REDIS_HOST:}
  port: ${REDIS_PORT:}
  useSearch: ${REDIS_USE_SEARCH:false}
  indexPrefix: ${REDIS_INDEX_PREFIX:synara}
imageCache:
  url: ${IMAGE_CACHE_URL:}
  token: ${IMAGE_CACHE_TOKEN:}
jwt:
  issuer: ${JWT_ISSUER:synara}
  audience: ${JWT_AUDIENCE:synara-api}
  realm: ${JWT_REALM:Access to 'Synara-API'}
  secret: ${JWT_SECRET:changeme}
storage:
  driverClassName: ${DB_DRIVER:org.sqlite.JDBC}
  jdbcURL: ${DB_URL:jdbc:sqlite:data.db}
  user: ${DB_USER:}
  password: ${DB_PASSWORD:}
audio:
  tracks: ${AUDIO_TRACKS_PATH:music/tracks}
  albums: ${AUDIO_ALBUMS_PATH:music/albums}
  playlists: ${AUDIO_PLAYLISTS_PATH:music/playlists}
  transcode: ${AUDIO_TRANSCODE_PATH:music/transcode}
  autoTranscode: ${AUDIO_AUTO_TRANSCODE_QUALITIES:}
  autoTranscodeAac: ${AUDIO_AUTO_TRANSCODE_QUALITIES_AAC:}
  custom: ${AUDIO_CUSTOM_PATH:music/custom}
  secondary-tracks:
    - ${AUDIO_TRACKS_SECONDARY_PATH:}
transcriber:
  url: ${TRANSCRIBER_URL:http://localhost:8000}
data:
  images: ${DATA_IMAGES_PATH:data/images}
spotify:
  clientId: ${SPOTIFY_CLIENT_ID:}
  clientSecret: ${SPOTIFY_CLIENT_SECRET:}
tidal:
  clientId: ${TIDAL_CLIENT_ID:}
  clientSecret: ${TIDAL_CLIENT_SECRET:}
appleMusic:
  teamId: ${APPLE_MUSIC_TEAM_ID:}
  keyId: ${APPLE_MUSIC_KEY_ID:}
  p8Path: ${APPLE_MUSIC_P8_PATH:}
proxy:
  hostname: ${PROXY_HOSTNAME:}
  controlPort: ${PROXY_CONTROL_PORT:8081}
  ssl: ${PROXY_SSL:false}
  name: ${PROXY_NAME:}
  id: ${PROXY_ID:}
  key: ${PROXY_KEY:}
youtube:
  apiKey: ${YOUTUBE_API_KEY:}
ytdlp:
  config: ${YTDLP_CONFIG_PATH:}
workers:
  threadMultiplier: ${WORKER_THREAD_MULTIPLIER:1.0}
