enable_cache = true
debug = false


[templates]
default = "Tracks/{album.id}/{item.id}"


[download]
track_quality = "max"
video_quality = "fhd"
skip_existing = false
threads_count = 3
download_path = "/data/Synara/tiddl"
singles_filter = "none"
videos_filter = "none"
atmos_filter = "allow"
update_mtime = false
rewrite_metadata = false


[metadata]
enable = true
lyrics = true
cover = true
album_review = false


[cover]
save = false
size = 1280
allowed = []


[cover.templates]

[m3u]
save = false
allowed = ["album", "mix", "playlist"]

[m3u.templates]
album = "m3u/{type}/{album.artist} - {album.title}"
playlist = "m3u/{type}/{playlist.title}"
mix = "m3u/{type}/{now:%x}"
