package dev.dertyp.docs

import dev.dertyp.core.API_KEY_HEADER
import dev.dertyp.core.API_KEY_QUERY
import dev.dertyp.core.ClientFeature
import dev.dertyp.core.FeatureDoc
import dev.dertyp.data.ApiVersion
import dev.dertyp.services.ApiKeyScopeRegistry
import dev.dertyp.services.JwtService
import dev.dertyp.services.subsonic.SubsonicPlugin
import dev.dertyp.ui.UiComponent
import dev.dertyp.ui.UiSchema
import dev.dertyp.ui.UiSchemaVersion
import kotlinx.serialization.SerialName
import java.io.File
import kotlin.reflect.KClass
import kotlin.time.DurationUnit

private const val HEADLINE = "# Synara API Constants"

private const val GENERATED_BY =
    "This document is generated by `./gradlew generateDocs` (task `:server:generateApiConstantsDocs`) from the server sources. Do not edit by hand."

private const val POINTERS =
    "Guides: [API_VERSIONING.md](API_VERSIONING.md) · [AUTHENTICATION.md](AUTHENTICATION.md) · Index: [README.md](README.md)"

private fun code(value: String) = "`$value`"

private fun featureDoc(feature: ClientFeature): FeatureDoc? =
    ClientFeature::class.java.getField(feature.name).getAnnotation(FeatureDoc::class.java)

private fun wireName(kClass: KClass<out UiComponent>): String =
    kClass.java.getAnnotation(SerialName::class.java)?.value ?: kClass.simpleName.orEmpty()

private fun StringBuilder.table(headers: List<String>, rows: List<List<String>>) {
    appendLine(headers.joinToString(" | ", prefix = "| ", postfix = " |"))
    appendLine(headers.joinToString("|", prefix = "|", postfix = "|") { "---" })
    rows.forEach { appendLine(it.joinToString(" | ", prefix = "| ", postfix = " |")) }
}

private fun buildDocument(): String = buildString {
    appendLine(HEADLINE)
    appendLine()
    appendLine(GENERATED_BY)
    appendLine()
    appendLine(POINTERS)
    appendLine()

    appendLine("## API version")
    appendLine()
    table(
        listOf("Constant", "Value"),
        listOf(
            listOf(code("ApiVersion.HEADER"), code(ApiVersion.HEADER)),
            listOf(code("ApiVersion.LEGACY"), code(ApiVersion.LEGACY.toString())),
            listOf(code("ApiVersion.CURRENT"), code(ApiVersion.CURRENT.toString())),
        ),
    )
    appendLine()

    appendLine("## Features")
    appendLine()
    table(
        listOf("Version", "Feature", "Introduces", "Older clients get", "Max version"),
        ClientFeature.entries.sortedBy { it.minApiVersion }.map {
            val doc = featureDoc(it)
            listOf(
                it.minApiVersion.toString(),
                code(it.name),
                doc?.introduces ?: "-",
                doc?.fallback ?: "-",
                it.maxApiVersion?.toString() ?: "-",
            )
        },
    )
    appendLine()

    appendLine("## UI schema version")
    appendLine()
    table(
        listOf("Constant", "Value"),
        listOf(
            listOf(code("UiSchemaVersion.HEADER"), code(UiSchemaVersion.HEADER)),
            listOf(code("UiSchemaVersion.NONE"), code(UiSchemaVersion.NONE.toString())),
            listOf(code("UiSchemaVersion.CURRENT"), code(UiSchemaVersion.CURRENT.toString())),
        ),
    )
    appendLine()
    table(
        listOf("Component", "Introduced in"),
        UiSchema.introducedIn
            .map { (kClass, version) -> wireName(kClass) to version }
            .sortedWith(compareBy({ it.second }, { it.first }))
            .map { listOf(code(it.first), it.second.toString()) },
    )
    appendLine()

    appendLine("## Authentication")
    appendLine()
    table(
        listOf("Constant", "Value"),
        listOf(
            listOf("Access token lifetime", code(JwtService.ACCESS_TOKEN_LIFETIME.toString(DurationUnit.HOURS))),
            listOf("Refresh token lifetime", code(JwtService.REFRESH_TOKEN_LIFETIME.toString(DurationUnit.DAYS))),
            listOf("JWT claim for username", code(JwtService.CLAIM_USERNAME)),
            listOf("JWT claim for session id", code(JwtService.CLAIM_SESSION)),
            listOf("Cookie name", code(JwtService.AUTH_COOKIE)),
            listOf("API key query parameter", code(API_KEY_QUERY)),
            listOf("API key header", code(API_KEY_HEADER)),
        ),
    )
    appendLine()
    appendLine("### API key scopes")
    appendLine()
    val registry = ApiKeyScopeRegistry()
    val subsonic = SubsonicPlugin()
    registry.forPlugin(subsonic.id).registerScope(SubsonicPlugin.SCOPE)
    table(
        listOf("Scope", "Name", "Description", "Registered by"),
        registry.all().map { listOf(code(it.id), it.name, it.description, code(it.source)) },
    )
}

fun main(args: Array<String>) {
    val target = File(args.firstOrNull() ?: "docs/API_CONSTANTS.md")
    val content = buildDocument()
    if (target.exists() && target.readText() == content) {
        println("docs/API_CONSTANTS.md is up to date.")
        return
    }
    target.parentFile?.mkdirs()
    target.writeText(content)
    println("Wrote ${target.path}")
}
