S = "server/src/main/kotlin/dev/dertyp/"
C = "common-rpc/src/commonMain/kotlin/dev/dertyp/"
CS = "credential-server/src/main/kotlin/dev/dertyp/credentials/server/"
PX = "proxy/src/main/kotlin/dev/dertyp/proxy/"
LB = "listen-backup/src/main/kotlin/dev/dertyp/listenbackup/"
UI = S + "services/ui/credentialserver/"

GROUPS = [
    {"id": "clients", "label": "Clients", "column": 0, "cols": 1,
     "desc": "Everything that opens a connection to a Synara process. Client code lives in other repositories, only the endpoints are verified here."},
    {"id": "relay", "label": "Relay and mock", "column": 1, "cols": 1,
     "desc": "Standalone processes that sit in front of or stand in for the server."},
    {"id": "entry", "label": "Server entry points", "column": 2, "cols": 1,
     "desc": "Every HTTP and WebSocket surface of the :server process."},
    {"id": "core", "label": "Server subsystems", "column": 3, "cols": 2,
     "desc": "Parts of the :server process that own a link to something outside it."},
    {"id": "satellites", "label": "Synara satellites", "column": 4, "cols": 1,
     "desc": "Separate Synara processes the server calls."},
    {"id": "sidecars", "label": "Sidecars", "column": 4, "cols": 1,
     "desc": "Python containers next to the server."},
    {"id": "stores", "label": "Datastores and volumes", "column": 4, "cols": 2,
     "desc": "Databases, caches and shared directories."},
    {"id": "tools", "label": "Command-line tools", "column": 4, "cols": 2,
     "desc": "Started by the server as subprocesses through ExternalTool and ProcessBuilder."},
    {"id": "external", "label": "External services", "column": 5, "cols": 2,
     "desc": "Third-party hosts on the internet."},
    {"id": "lan", "label": "Local network", "column": 5, "cols": 1,
     "desc": "Things reached on the local network segment."},
]

STYLES = [
    {"kind": "always", "dash": "", "label": "present in every setup"},
    {"kind": "optional", "dash": "dash", "label": "enabled by configuration, a credential or a user action"},
    {"kind": "local", "dash": "dot", "label": "not a network link (in-process, subprocess, files)"},
]


def node(id, label, group, desc, sub=None, meta=None, src=None, flags=None):
    item = {"id": id, "label": label, "group": group, "desc": desc, "meta": meta or []}
    if sub:
        item["sub"] = sub
    if src:
        item["src"] = src
    if flags:
        item["flags"] = flags
    return item


def flow(title, transport, carries, src, trigger=None, config=None):
    item = {"title": title, "transport": transport, "carries": carries, "src": src}
    if trigger:
        item["trigger"] = trigger
    if config:
        item["config"] = config
    return item


def edge(source, target, label, kind, *flows):
    return {"from": source, "to": target, "label": label, "kind": kind, "flows": list(flows)}


def nodes():
    return [
        node("apps", "Synara apps", "clients",
             "Desktop and mobile apps built on common-rpc. They speak kRPC over WebSocket and fetch audio and images over HTTP when they are not behind the proxy.",
             "kRPC clients", [["Reconnect", "ReconnectingRpcClient, 5 retries"], ["Observation backoff", "1 s to 30 s"]],
             C + "rpc/ReconnectingRpcClient.kt:46"),
        node("rest-clients", "REST clients", "clients",
             "Anything calling the generated REST layer. Every RPC method is also a REST route, flows arrive as server-sent events.",
             "HTTP + SSE", [], S + "routing/RestRegistry.kt:40"),
        node("browser", "Admin browser", "clients",
             "A browser on the mirror admin page or on the hand-written auth routes. The page carries its own login form and keeps the token in the synara-auth cookie.",
             "cookie synara-auth", [], "server/src/main/resources/static/mirror.js:40"),
        node("subsonic-clients", "Subsonic clients", "clients",
             "Third-party players using the Subsonic or OpenSubsonic API.", "/rest", [],
             S + "services/subsonic/SubsonicRoutes.kt:74"),
        node("mcp-clients", "MCP clients", "clients",
             "Assistants reading listen history through seven read-only tools.", "API key scope mcp", [],
             S + "mcp/ListenHistoryMcpServer.kt:202"),
        node("radio-players", "Radio players", "clients",
             "Any player that can pull an endless AAC stream with ICY metadata.", "API key scope radio", [],
             S + "routing/RadioRoutes.kt:40"),
        node("dev-clients", "Client developers", "clients",
             "Client builds pointed at the mock server during development.", None, [],
             "mock-server/src/main/kotlin/dev/dertyp/mock/Main.kt:43"),
        node("operator", "Operator and probes", "clients",
             "Health probes, OpenAPI readers and the person running the credential server CLI.", None, [],
             S + "Routing.kt:63"),

        node("proxy", "proxy", "relay",
             "Public WebSocket relay. Each server dials out to it and clients reach that server through the tunnel. It relays only kRPC WebSockets, so REST, images, radio, Subsonic and MCP never pass through it.",
             "port 8081", [["Modules", ":proxy, :common-proxy"], ["Frame", "1 byte type, 16 byte client id, 1 byte subtype, payload"],
                           ["Queues", "Channel.UNLIMITED send queues, maxFrameSize Long.MAX_VALUE"]],
             PX + "Application.kt:72"),
        node("mock-server", "mock-server", "relay",
             "Standalone Ktor app that registers a reflection mock for every interface in the generated service registry, with MockUiService for IUiService. No compose file includes it.",
             "port 8081", [["Module", ":mock-server"], ["Missing", "/handshake, legacy wire, file streaming, radio, MCP, Subsonic"]],
             "mock-server/src/main/kotlin/dev/dertyp/mock/Main.kt:43"),

        node("ep-handshake", "WS /handshake", "entry",
             "Sends one binary CBOR HandshakeResponse with secure, sslSupported, apiVersion and uiSchemaVersion, then closes. No auth.",
             "public", [], S + "Routing.kt:140"),
        node("ep-rpc-public", "kRPC /rpc, /rpc/auth", "entry",
             "kRPC over WebSocket with CBOR. Both paths register the same three public services: IServerStatsService, IAuthService, IHandshakeService.",
             "3 public services", [["Encoding", "CBOR, legacy wire below API version 8"]], S + "routing/RpcRegistry.kt:94"),
        node("ep-rpc-auth", "kRPC /rpc/services", "entry",
             "The authenticated kRPC surface with 50 services. The upgrade answers 401 without a valid token. Every service is wrapped per connection with client compat, metrics when the collector is enabled, caching, logging and authorization.",
             "50 services, JWT", [["Wrapper order", "withClientCompat, withMetrics, withCaching, withLogging, withAuthorization"],
                                 ["Permissions", "@RequiresAdmin and @RequiresCapability (IMPORT, EDIT, DELETE, PODCAST_EDIT)"]],
             S + "Routing.kt:147"),
        node("ep-rest", "Generated REST", "entry",
             "The same service methods as HTTP routes under /<service>. Response kinds are JSON, UNIT, BYTES, BYTE_FLOW, SSE and FILE. It carries the ranged audio file routes and the public image routes. A ByteArray in a request body is a JSON array of numbers.",
             "54 services, JWT or public", [["Public block", "/serverStats, /auth, /handshake/handshake, /image, /animatedImage"],
                                           ["Wrappers", "client compat and authorization only"]],
             S + "routing/RestRegistry.kt:28"),
        node("ep-auth-rest", "Auth routes", "entry",
             "Hand-written JSON routes: POST /authenticate and /refresh-token without auth, POST /register for admins, GET /userInfo, GET /sessions, DELETE /sessions/{sessionId}.",
             "/authenticate, /sessions", [], S + "services/JwtService.kt:115"),
        node("ep-radio", "Radio routes", "entry",
             "GET /radio/stream, /radio/{sessionId}/stream and /radio/channel/{channelId}/stream. Endless audio/aac ADTS with optional ICY metadata.",
             "/radio/**", [["Auth", "API key with scope radio"]], S + "routing/RadioRoutes.kt:40"),
        node("ep-mcp", "MCP route", "entry",
             "POST /mcp, stateless Streamable HTTP with JSON responses. GET and DELETE answer 405.",
             "POST /mcp", [["Auth", "API key with scope mcp"]], S + "routing/McpRoutes.kt:54"),
        node("ep-subsonic", "Subsonic plugin", "entry",
             "32 authenticated endpoints plus getOpenSubsonicExtensions under /rest, each as GET and POST, with and without .view. Mounted by the built-in SubsonicPlugin through IRoutePlugin outside the JWT block.",
             "/rest/*", [["Auth", "apiKey scope subsonic, or u+t+s, or u+p"]], S + "services/subsonic/SubsonicRoutes.kt:24"),
        node("ep-mirror-admin", "Mirror admin", "entry",
             "GET /admin/mirror serves an HTML page with its own login form. The control API under /admin/mirror needs a JWT and an admin user. Progress is a server-sent event stream.",
             "/admin/mirror", [["Static", "/static/mirror.js"]], S + "routing/Mirror.kt:88"),
        node("ep-health", "Health and docs", "entry",
             "KHealth with an available check and the readiness checks indexer_ready and transcoder_ready, plus GET /api.json and /swagger.",
             "KHealth, /api.json", [], S + "Routing.kt:63"),

        node("s-auth", "Auth and sessions", "core",
             "JwtService, SessionService, ApiKeyService and the Subsonic authenticator. Access tokens are HS256 JWTs valid 24 h, refresh tokens last 30 days, and validation requires an active session row.",
             "JWT, API keys", [["Tables", "user, user_capability, session, refreshToken, apiKey, subsonicCredential"]],
             S + "services/JwtService.kt:84"),
        node("s-domain", "Domain services", "core",
             "The Koin singletons behind the RPC adapters: library, listening, playback, queue, radio, discovery, UI and admin services. Push to clients is always a kRPC Flow or SSE fed from here.",
             "library, listening, UI", [["Push", "ChangeNotifier topics, queue sync, remote control, client requests"]],
             S + "routing/RpcRegistry.kt:184"),
        node("s-plugins", "Plugin manager", "core",
             "Loads eight built-in plugins, then plugins/*.jar through URLClassLoader and ServiceLoader. Plugins contribute importers, indexers, routes, UI, hooks and credentials.",
             "plugin API version 4", [["Built-in", "Tidal, Youtube, Soundcloud, Gamdl, MusicBrainz, Recommendation, Subsonic, PodcastIndex"]],
             S + "plugins/PluginManager.kt:59"),
        node("s-credentials", "Credentials", "core",
             "RoutingCredentialProvider over the local encrypted store and the remote credential server. A name is fetched remotely only when it is in the grants of the last token exchange.",
             "local or remote per name", [["Local store", "settings rows encrypted with CREDENTIALS_ENCRYPTION_KEY, then env"],
                                         ["Cache", "API keys 5 min, tokens until expiry minus 60 s, files never"]],
             S + "services/credentials/RoutingCredentialProvider.kt:10"),
        node("s-import", "Import service", "core",
             "ImportService, ImporterProxy, JobService and UpcomingReleaseImportService. Classifies the input as URL, ISRC or UPC, picks the importer and queues the job.",
             "queue and importer choice", [["Importer choice", "canHandle, then MusicBrainz sibling URLs, then LinkResolver, else the default importer"]],
             S + "services/import/ImporterProxy.kt:41"),
        node("s-tidal-importer", "Tidal importer", "core",
             "TidalBaseImporter. Before the download it fetches Tidal metadata, matches a MusicBrainz release and picks a cover. After it, files are tagged with jaudiotagger and handed to the indexer.",
             "TidalBaseImporter", [], S + "services/import/TidalBaseImporter.kt:129"),
        node("s-tiddl", "tiddl runner", "core",
             "TiddlService. Runs tiddl download url, download fav and auth login. When importer.tiddl is managed remotely, the auth file is written before each run.",
             "TiddlService", [], S + "services/import/TiddlService.kt:18"),
        node("s-tdn", "tidal-dl-ng runner", "core",
             "TdnService. Runs tdn dl, dl_fav and login. On FileNotFoundError it deletes the broken file and retries.",
             "TdnService", [], S + "services/import/TdnService.kt:30"),
        node("s-gamdl", "gamdl runner", "core",
             "GamdlService. Runs gamdl with a cookies file and an optional Widevine device file, then transcodes each new .m4a to AUDIO_LOSSLESS_FORMAT (FLAC, WAV or AIFF).",
             "GamdlService", [], S + "services/gamdl/GamdlService.kt:77"),
        node("s-ytdlp", "YouTube and SoundCloud", "core",
             "YoutubeService, YoutubeApiService and SoundcloudService. SoundCloud has no HTTP API here, it is yt-dlp only. Without a YouTube API key the metadata comes from yt-dlp -J.",
             "yt-dlp importers", [], S + "services/youtube/YoutubeService.kt:58"),
        node("s-metadata", "Provider clients", "core",
             "TidalService, AppleMusicService, SpotifyService, DeezerService, TheAudioDBService, AcoustIdService, LinkResolverService, ImageCacheService and MetadataFetchingService. Artist image fallback order is TheAudioDB, Tidal, Deezer, Apple, Spotify.",
             "metadata lookups", [["Tidal retry", "5 retries, 5 s exponential backoff capped at 2 min"]],
             S + "services/MetadataFetchingService.kt:37"),
        node("s-musicbrainz", "MusicBrainz and mirror", "core",
             "MusicBrainzService behind CachedMusicBrainzService. Reads the mb_* tables first and writes through on a miss. Rows older than 90 days are refetched at low priority.",
             "mb_* read-through", [["Workers", "MusicBrainzWorker 0 0 * * *, MusicBrainzCacheWorker after it"]],
             S + "services/metadata/MusicBrainzService.kt:645"),
        node("s-releases", "Releases", "core",
             "ReleaseService, AppleMusicReleaseService, AppleMusicArtistResolver and ProviderLinkService. Builds the release feed for followed and library artists and resolves provider links.",
             "release feed", [["Workers", "RecentReleaseWorker 0 1 * * *, AppleMusicReleaseWorker 0 6 * * *"]],
             S + "services/ReleaseService.kt:930"),
        node("s-lyrics", "Lyrics", "core",
             "LrcLibService, LyricsService and LyricsSearch. LRCLIB lookups run nightly, WhisperX transcription is disabled by default.",
             "LRCLIB, WhisperX", [["Workers", "LrcLibWorker 30 4 * * *, LyricsSyncWorker 0 4 * * * (disabled)"]],
             S + "services/LyricsService.kt:52"),
        node("s-audio", "Audio analysis", "core",
             "AudioAnalysisService, FlacAnalysisService, PcmAnalysisService and the Transcoder. Transcoding, Atmos detection and RMS envelopes run in-process through JavaCV, only the tools shown here are subprocesses.",
             "Essentia, FLAC, PCM", [["Workers", "AudioAnalysisWorker 0 3 * * *, FlacAnalysisWorker 0 5 * * *, PcmAnalysisWorker 20 5 * * *"]],
             S + "services/AudioAnalysisService.kt:62"),
        node("s-embeddings", "Audio embeddings", "core",
             "AudioEmbeddingService. Sends batches of 16 file paths and stores the vectors as float32 blobs in song_audio_embedding.",
             "AudioEmbeddingService", [["Worker", "AudioEmbeddingWorker after audio-analysis"]],
             S + "services/schedule/AudioEmbeddingWorker.kt:36"),
        node("s-recommendation", "Recommendations", "core",
             "RecommendationService writes training data and reads the embeddings back. RecommendationServingService serves similar songs, mixes and moods to RadioService and DiscoveryService.",
             "training and serving", [["Worker", "RecommendationTrainWorker 0 7 * * *, only when dirty"]],
             S + "services/RecommendationService.kt:52"),
        node("s-podcasts", "Podcasts", "core",
             "PodcastFeedService, PodcastImportService, PodcastStreamService and PodcastIndexOrgIndex. Feed, enclosure, stream and transcript URLs pass requirePublicHttpUrl before they are fetched.",
             "feeds and episodes", [["Workers", "PodcastRefreshWorker 15 * * * *, PodcastImportWorker */15 * * * *"]],
             S + "services/podcast/PodcastFeedService.kt:50"),
        node("s-hue", "Hue", "core",
             "HueService, HueDiscoveryService and HueBridgeClient. Driven by the NowPlayingChanged hook, it combines the cover palette with audio analysis and streams light frames.",
             "light sync", [["Light commands", "at most 8 per second"]], S + "services/hue/HueService.kt:519"),
        node("s-listenbrainz", "ListenBrainz sync", "core",
             "ListenBrainzService. Pulls listen history hourly and matches it to songs by MBID, ISRC and manual links. The only POST it makes is a manual mapping.",
             "pull only", [["Worker", "ListenBrainzSyncWorker 0 * * * *"]], S + "services/sync/ListenBrainzService.kt:243"),
        node("s-listen-backup", "Listen backup sender", "core",
             "ListenBackupService. Sends locally recorded listens one way, in batches with a persisted cursor.",
             "one-way", [["Worker", "ListenBackupWorker 30 * * * *"], ["Config", "row listen_backup_config, not env"]],
             S + "services/sync/ListenBackupService.kt:220"),
        node("s-tidal-sync", "Tidal favourites sync", "core",
             "TidalSyncService. Per-user PKCE login, then a user-triggered pull of liked tracks that are imported through the Tidal importer.",
             "per-user OAuth", [["Tables", "syncService, favSync"]], S + "services/sync/TidalSyncService.kt:75"),
        node("s-reverse-proxy", "Reverse proxy client", "core",
             "ReverseProxyService. Dials out to the proxy and creates an in-process KrpcServer over a MultiplexedTransport for each tunnelled client.",
             "outbound tunnel", [["Keepalive", "Ping every 10 s, close after 30 s of silence"], ["Reconnect", "5 s delay after a failed connection"]],
             S + "services/ReverseProxyService.kt:122"),
        node("s-remote-mirror", "Remote mirror", "core",
             "RemoteMirrorService. Pulls a library from another Synara server with admin credentials: users, images, artists, albums, songs, playlists, likes. One mirror at a time.",
             "pull from another server", [["Audio", "64 KB chunks, 3 parallel downloads"]], S + "services/RemoteMirrorService.kt:222"),
        node("s-mirror-source", "Mirror source", "core",
             "MirrorService behind IMirrorService. Serves paths, entity flows, password hashes and song data to a mirroring server. Every method needs an admin.",
             "IMirrorService", [], S + "services/MirrorService.kt:52"),
        node("s-search", "Search indexing", "core",
             "SearchIndexWorker, RedisSearchService and SearchIndexRemover. On PostgreSQL triggers fill search_index_queue and a continuous loop rebuilds the tsvector columns. On SQLite the worker is not started.",
             "PostgreSQL only", [["Loop", "2 s idle poll, batches of 100"]], S + "services/SearchIndexWorker.kt:22"),
        node("s-images", "Images and blob cache", "core",
             "ImageService and AnimatedImageService. Image bytes are cached in Redis without a TTL and lost bytes are re-downloaded from the stored origin URL.",
             "covers, animated covers", [["Worker", "ImageAnalysisWorker"]], S + "services/ImageService.kt:208"),
        node("s-backup", "Backup and restore", "core",
             "BackupService, DbManagementService and UserPlaylistBackupService. A backup is a zip with a zstd CBOR dump, an inventory of the audio directories and an image index, plus deduplicated image blobs. Audio files are not copied.",
             "local directory only", [["Workers", "DatabaseBackupWorker and UserPlaylistBackupWorker 0 2 * * *"], ["Rotation", "keeps 10 zips"]],
             S + "services/BackupService.kt:156"),
        node("s-http-queue", "Outbound HTTP queue", "core",
             "HttpClientQueueService. One mutex and priority queue per host with a minimum spacing: MusicBrainz 1 s, YouTube and googleapis 1 s, TheAudioDB 500 ms, AcoustID 340 ms, Deezer, Spotify and Apple 100 ms, LinkResolver and ListenBrainz 10 ms, others 250 ms. Rate limit headers can widen the spacing. A 429 is sent again until three requests were made.",
             "per-host pacing", [["Priorities", "HIGH, NORMAL, LOW"]], S + "core/HttpClient.kt:131"),
        node("s-db", "Database access", "core",
             "DatabaseManager and dbQuery. HikariCP pool of 1 on SQLite with WAL, 100 otherwise. MigrationBaseCheck runs before Flyway and halts the JVM when the database is not at the base.",
             "HikariCP, Flyway", [["Base", "1.109"]], S + "services/DatabaseManager.kt:49"),
        node("s-jmdns", "mDNS advertiser", "core",
             "JmDNSPlugin. Registers the service synara-api on the configured port at ApplicationStarted with no TXT properties.",
             "JmDNSPlugin", [], S + "plugins/JmDNSPlugin.kt:48"),

        node("cred-server", "credential-server", "satellites",
             "Central broker for third-party credentials with one client per Synara server. It exchanges OAuth client credentials, refreshes Tidal sessions on every hand-out, signs Apple developer tokens and stores importer auth files. Its work happens on demand, when a credential is fetched or an admin acts.",
             "port 8083", [["Modules", ":credential-server, :common-credentials"], ["Presets", "12"],
                           ["Consumer token", "ES256 JWT, 900 s"], ["Encryption", "AES-256-GCM, CREDENTIAL_SERVER_MASTER_KEY"]],
             CS + "Application.kt:50"),
        node("listen-backup", "listen-backup", "satellites",
             "Receiver that stores a copy of the listen history in one table. Without BACKUP_KEY it accepts uploads unauthenticated and logs a warning at startup.",
             "port 8082", [["Modules", ":listen-backup, :common-listen-backup"], ["Routes", "GET /health, GET /status, POST /listens"]],
             LB + "Application.kt:53"),
        node("other-server", "another Synara server", "satellites",
             "A second server. This server can pull a library from it, and it can pull from this one through IMirrorService.",
             "mirror peer", [], S + "services/RemoteMirrorService.kt:110"),

        node("transcriber", "transcriber", "sidecars",
             "FastAPI with Demucs, faster-whisper medium and WhisperX alignment. CUDA when available. It reads audio by absolute path, so it mounts the music directory at the same path as the server.",
             "port 8000", [["Routes", "GET /health, POST /transcribe"]], "transcriber/main.py:53"),
        node("audio-embed", "audio-embed", "sidecars",
             "FastAPI with Essentia TensorflowPredictMusiCNN. Returns one mean-pooled, normalised vector per path.",
             "port 8200", [["Routes", "GET /health, POST /embed"], ["Model", "msd-musicnn_v1"]], "audio-embed/main.py:40"),
        node("recsys", "recsys", "sidecars",
             "Python loop without HTTP. Trains Word2Vec on playlist, album and listen sequences, maps cold songs from audio vectors with Ridge, and clusters into moods.",
             "no port", [["Poll", "every 5 s for request.ready"]], "recsys/main.py:124"),
        node("pot-provider", "pot-provider", "sidecars",
             "bgutil-ytdlp-pot-provider container. It appears only in docker-compose.server.yml and no server code references it.",
             "compose only", [], "docker-compose.server.yml:77", ["unverified"]),

        node("db", "PostgreSQL / SQLite", "stores",
             "The server database. SQLite data.db by default, PostgreSQL in every compose file that starts the server.", "port 5432", [],
             S + "services/DatabaseManager.kt:56"),
        node("redis", "Redis cluster", "stores",
             "Reached through Jedis RedisClusterClient. Four clients are created: the cache provider, ImageService, AnimatedImageService and TidalService. Image blob keys are written without a TTL.",
             "ports 7000-7005", [["Keys", "image:, releaseImage:, animated:, tidal_track::, tidal_album::, tidal_artist::, tidal_playlist::"]],
             S + "plugins/RedisCacheProvider.kt:18"),
        node("cred-db", "credentials database", "stores",
             "SQLite by default or PostgreSQL. Tables cs_client, cs_credential, cs_grant and cs_signing_key.", "SQLite", [],
             CS + "db/Tables.kt:9"),
        node("backup-db", "listen backup database", "stores",
             "One table backup_listen. SQLite by default or PostgreSQL.", "SQLite", [], LB + "ListenBackupStore.kt:16"),
        node("backup-dir", "backup directory", "stores",
             "BACKUP_DIR, default ~/.config/backups. Holds the zips, blobs/ and user-playlists/. Not shared with any other container.",
             "BACKUP_DIR", [], S + "config/ServerConfig.kt:147"),
        node("music-dir", "music directory", "stores",
             "The library bind mount. Shared with the transcriber read-write and with audio-embed read-only.", "/data", [],
             "docker-compose.yml:28"),
        node("recsys-volume", "recsys volume", "stores",
             "RECSYS_DATA_DIR on the server and /data in recsys are the same volume.", "RECSYS_DATA_DIR", [],
             "docker-compose.yml:31"),

        node("tiddl", "tiddl", "tools",
             "Tidal downloader, installed from a patched fork so downloads reach max quality.", "python3 -u", [],
             "Dockerfile.nobuild:79"),
        node("tdn", "tidal-dl-ng", "tools",
             "Tidal downloader, binary tdn. Installed only by the full Dockerfile.", "tdn", [], "Dockerfile:75"),
        node("gamdl", "gamdl", "tools",
             "Apple Music downloader. Neither Dockerfile installs it.", None, [], S + "services/gamdl/GamdlService.kt:49"),
        node("ytdlp", "yt-dlp", "tools",
             "YouTube and SoundCloud downloader. Installed only by Dockerfile.nobuild.", None, [], "Dockerfile.nobuild:79"),
        node("ffmpeg", "ffmpeg / ffprobe", "tools",
             "The CLI is used for PCM analysis and the gamdl transcode. Everything else uses in-process JavaCV.", None, [],
             S + "services/PcmAnalysisService.kt:19"),
        node("fpcalc", "fpcalc", "tools", "Chromaprint fingerprint and duration as JSON.", None, [],
             S + "services/metadata/AcoustIdFingerprintService.kt:16"),
        node("essentia", "essentia extractor", "tools",
             "essentia_streaming_extractor_music. Only Dockerfile.nobuild copies the binary.", None, [],
             "Dockerfile.nobuild:51"),
        node("metaflac", "metaflac", "tools", "FLAC stream info and seek point repair.", None, [],
             S + "services/FlacAnalysisService.kt:14"),
        node("syncedlyrics", "syncedlyrics", "tools", "Python module that searches lyrics providers, capped at 5 minutes.", None, [],
             S + "services/LyricsSearch.kt:18"),

        node("tidal-api", "Tidal API", "external", "openapi.tidal.com/v2, JSON:API.", "openapi.tidal.com", [],
             S + "services/metadata/TidalService.kt:107"),
        node("tidal-auth", "Tidal auth", "external",
             "auth.tidal.com token endpoint: client credentials, refresh token and device authorization.", "auth.tidal.com", [],
             CS + "broker/TidalAuthApi.kt:37"),
        node("tidal-login", "Tidal login", "external", "login.tidal.com/authorize for the per-user PKCE flow.", "login.tidal.com", [],
             S + "services/sync/TidalSyncServiceBase.kt:45"),
        node("musicbrainz", "MusicBrainz", "external", "musicbrainz.org/ws/2, paced at one request per second.", "musicbrainz.org", [],
             S + "services/metadata/MusicBrainzService.kt:63"),
        node("caa", "Cover Art Archive", "external", "Front covers for releases and release groups. No auth.", "coverartarchive.org", [],
             S + "services/metadata/MusicBrainzMetadataService.kt:157"),
        node("itunes", "iTunes Search", "external", "itunes.apple.com search and lookup. No auth.", "itunes.apple.com", [],
             S + "services/metadata/AppleMusicService.kt:58"),
        node("apple-catalog", "Apple Music catalog", "external",
             "api.music.apple.com catalog endpoints. Needs a developer token.", "api.music.apple.com", [],
             S + "services/metadata/AppleMusicService.kt:95"),
        node("mzstatic", "Apple artwork", "external", "Artwork files on mzstatic.com, fetched outside the queue.", "mzstatic.com", [],
             S + "services/release/AppleMusicReleaseService.kt:869"),
        node("spotify-api", "Spotify API", "external", "api.spotify.com/v1/search only.", "api.spotify.com", [],
             S + "services/metadata/SpotifyService.kt:27"),
        node("spotify-accounts", "Spotify accounts", "external", "accounts.spotify.com/api/token for client credentials.",
             "accounts.spotify.com", [], CS + "broker/CredentialPresets.kt:14"),
        node("deezer", "Deezer", "external", "api.deezer.com artist search, ISRC and UPC lookups. No auth.", "api.deezer.com", [],
             S + "services/metadata/DeezerService.kt:15"),
        node("audiodb", "TheAudioDB", "external", "Genres, biographies and images for entities with MBIDs. Default key 123.",
             "theaudiodb.com", [], S + "services/metadata/TheAudioDBService.kt:28"),
        node("acoustid", "AcoustID", "external", "Fingerprint lookup. Accepts a score of at least 0.85 within 3 s of duration.",
             "api.acoustid.org", [], S + "services/metadata/AcoustIdService.kt:75"),
        node("lrclib", "LRCLIB", "external", "lrclib.net/api/get. No auth.", "lrclib.net", [], S + "services/LrcLibService.kt:13"),
        node("youtube-api", "YouTube Data API", "external", "googleapis.com/youtube/v3 videos, playlistItems and playlists.",
             "googleapis.com", [], S + "services/youtube/YoutubeApiService.kt:92"),
        node("youtube-music", "YouTube Music page", "external", "Queued GET of the watch page to read the og:image cover.",
             "music.youtube.com", [], S + "services/youtube/YoutubeApiService.kt:132"),
        node("linkresolver", "LinkResolver", "external", "linkresolver.synara.audio. Turns a URL, ISRC or UPC into platform links.",
             "linkresolver.synara.audio", [], S + "services/metadata/LinkResolverService.kt:24"),
        node("image-cache", "Image cache", "external", "Remote image store addressed by IMAGE_CACHE_URL and the image hash.",
             "IMAGE_CACHE_URL", [], S + "services/metadata/ImageCacheService.kt:40"),
        node("podcast-index", "Podcast Index", "external", "api.podcastindex.org search by term.", "api.podcastindex.org", [],
             S + "services/podcast/index/PodcastIndexOrgIndex.kt:114"),
        node("podcast-hosts", "Podcast hosts", "external", "Feed, artwork, enclosure and transcript hosts named by the feeds.",
             "feeds and enclosures", [], S + "services/podcast/PodcastHttp.kt:46"),
        node("listenbrainz", "ListenBrainz", "external", "api.listenbrainz.org/1.", "api.listenbrainz.org", [],
             S + "services/sync/ListenBrainzService.kt:474"),
        node("hue-cloud", "Hue discovery cloud", "external", "discovery.meethue.com, asked on every discovery next to mDNS.",
             "discovery.meethue.com", [], S + "services/hue/HueDiscoveryService.kt:114"),

        node("hue-bridge", "Philips Hue bridge", "lan",
             "Reached at https://{ip} with a certificate fingerprint pinned on first use, and over DTLS for the entertainment stream.",
             "HTTPS and UDP 2100", [], S + "services/hue/HueBridgeClient.kt:55"),
        node("mdns", "mDNS", "lan", "Multicast DNS on the local segment.", "UDP 5353", [], S + "plugins/JmDNSPlugin.kt:48"),
    ]


def edges():
    return [
        edge("apps", "ep-handshake", "WebSocket", "always",
             flow("Handshake", "WS /handshake, one binary CBOR frame", "secure, sslSupported, apiVersion, uiSchemaVersion",
                  S + "Routing.kt:140", "first contact")),
        edge("apps", "ep-rpc-public", "kRPC / WS", "always",
             flow("Login, refresh and device session", "kRPC over WebSocket at /rpc/auth, CBOR",
                  "IAuthService.authenticate checks BCrypt and creates a session row with User-Agent and IP. createDeviceSession mints a second session.",
                  S + "services/RpcAuthService.kt:20", "login, token refresh"),
             flow("Server stats, health and proxy address", "kRPC over WebSocket at /rpc, CBOR",
                  "IServerStatsService. getProxyInfo returns host, controlPort, ssl and id so the client can build the proxy base URL.",
                  S + "services/ServerStatsService.kt:130", "connect, validateServer with a 5 s timeout")),
        edge("apps", "ep-rpc-auth", "kRPC / WS", "always",
             flow("Service calls", "kRPC over WebSocket at /rpc/services with a Bearer token, CBOR",
                  "calls and server-streaming flows on 50 services. Headers X-Api-Version, X-Ui-Schema-Version, X-Time-Zone and Accept-Language are read from the connection request.",
                  S + "Routing.kt:147", "after login", "JWT_* settings"),
             flow("Audio over RPC", "kRPC Flow<ByteArray>", "ISongService.streamSong, downloadSong, streamSongAtmos and IPodcastService.streamEpisode as byte chunks. This is the only audio path through the proxy.",
                  C + "services/ISongService.kt:182", "playback"),
             flow("Change topics", "kRPC flow IChangeService.observeChanges",
                  "per-user topic pings ONLINE_DEVICES, HOME_CARDS, LISTENS, LISTENBRAINZ_STATUS, coalesced over 100 ms. The client re-reads the affected list.",
                  S + "core/ChangeNotifier.kt:17", "data change"),
             flow("Library changes since a time", "kRPC IEntityChangeService", "getWindow, allChanges and the filtered pulls, kept for ENTITY_CHANGE_RETENTION_DAYS (30)",
                  S + "services/RpcEntityChangeService.kt:26", "client sync", "API version 10"),
             flow("Shared queue between devices", "kRPC IQueueService writes plus observeQueue",
                  "versioned QueueInfo after each accepted write, with baseVersion conflicts", S + "services/QueueService.kt:86", "queue edits"),
             flow("Requests to another device", "kRPC flow IClientRequestService.connect, then complete",
                  "UploadQueue and ControlPlayback requests. Presence equals the lifetime of the stream.",
                  S + "services/ClientRequestService.kt:42", "another device asks"),
             flow("Remote control", "kRPC IRemoteControlService.sendCommand, reportStatus, observeStatus",
                  "playback commands with a 10 s ack timeout and status snapshots", S + "services/RemoteControlService.kt:21", "user action"),
             flow("Now playing and listens", "kRPC IScrobbleService", "nowPlaying, reportPlayback and listened. Writes trigger the LISTENS topic.",
                  S + "services/ScrobbleService.kt:43", "playback"),
             flow("Server-driven UI", "kRPC IUiService render, invoke, subscribe and subscribeLive",
                  "UI trees, live updates and actions, including the admin-only credential pages", C + "services/IUiService.kt:44", "page open",
                  "X-Ui-Schema-Version above 0"),
             flow("Importer credentials upload", "kRPC IImportService.setImportCredentials", "gamdl cookies and Widevine device file. Rejected when the name is managed remotely.",
                  S + "services/gamdl/GamdlService.kt:107", "admin action")),
        edge("apps", "ep-rest", "HTTP", "always",
             flow("Audio files", "HTTP GET and HEAD with Range", "/song/streamSong/{id}, /song/downloadSong/{id}, /song/streamSongAtmos/{id}, /podcast/streamEpisode/{episodeId}",
                  S + "routing/rest/RestCall.kt:259", "playback outside the proxy", "JWT header or cookie"),
             flow("Images", "HTTP GET, public", "/image/imageData/{id}?size, /animatedImage/imageData/{id}, /release/releaseImage/{releaseId}",
                  S + "routing/rest/RestCall.kt:215", "UI")),
        edge("rest-clients", "ep-rest", "REST + SSE", "always",
             flow("Service methods as REST", "HTTP JSON at /<service>/<method>", "the same methods as kRPC. Errors map to 400, 401, 403, 404 and 500.",
                  S + "routing/RestRegistry.kt:40", "per request"),
             flow("Flows as server-sent events", "SSE with a keep-alive comment every 5 s", "one JSON encoded item per data event for each Flow method, except Flow<ByteArray>",
                  S + "routing/rest/RestCall.kt:234", "subscribe"),
             flow("Uploads", "HTTP POST with JSON, a ByteArray is an array of numbers", "/image/image, /image/batch, /animatedImage/animatedImage, /customAudio/uploadCustomAudio",
                  "docs/CLIENT_REST.md:51", "user action", "EDIT capability for custom audio")),
        edge("browser", "ep-auth-rest", "HTTP JSON", "always",
             flow("Web login and sessions", "POST /authenticate, POST /refresh-token, POST /register, GET /userInfo, GET /sessions, DELETE /sessions/{sessionId}",
                  "token pairs and session rows", S + "services/JwtService.kt:115", "web login")),
        edge("browser", "ep-mirror-admin", "HTML + SSE", "always",
             flow("Mirror control page", "GET /admin/mirror, /static/mirror.js, POST /admin/mirror/{start,stop,reset,stats,remote-users,remote-playlists,remote-user-playlists,remote-instances}, GET /admin/mirror/local-users and /admin/mirror/remote-image/{imageId}, SSE /admin/mirror/progress",
                  "mirror control and progress", S + "routing/Mirror.kt:658", "admin", "cookie synara-auth, admin user")),
        edge("radio-players", "ep-radio", "HTTP stream", "always",
             flow("Radio stream", "HTTP GET /radio/**", "endless AAC, with ICY metadata every 16000 bytes when the request has Icy-MetaData: 1", S + "routing/RadioRoutes.kt:40",
                  "listener connects", "API key with scope radio")),
        edge("subsonic-clients", "ep-subsonic", "Subsonic", "always",
             flow("Subsonic API", "HTTP /rest/<name>[.view], GET and POST", "Subsonic XML or JSON, streams and cover art",
                  S + "services/subsonic/SubsonicRoutes.kt:74", "per request", "Subsonic credentials or an API key with scope subsonic")),
        edge("mcp-clients", "ep-mcp", "MCP / HTTP", "always",
             flow("Listen history tools", "POST /mcp, JSON-RPC", "seven read-only tools over the caller's listen history",
                  S + "routing/McpRoutes.kt:54", "tool call", "API key with scope mcp")),
        edge("operator", "ep-health", "HTTP", "always",
             flow("Health and OpenAPI", "KHealth routes, GET /api.json, GET /swagger", "liveness, readiness and the OpenAPI document",
                  S + "Routing.kt:63", "probes")),
        edge("operator", "cred-server", "CLI", "local",
             flow("Credential server CLI", "the jar started with arguments, working on the database directly",
                  "clients, credentials, signing keys and Tidal logins", CS + "cli/CredentialCli.kt:22", "manual")),
        edge("dev-clients", "mock-server", "kRPC + REST", "optional",
             flow("Mock API", "kRPC at /rpc, /rpc/auth and /rpc/services, REST at /<service>/<method>",
                  "dummy data from reflection mocks. Any Bearer header is accepted.", "mock-server/src/main/kotlin/dev/dertyp/mock/Main.kt:43",
                  "development")),
        edge("apps", "proxy", "kRPC / WS", "optional",
             flow("Tunnelled kRPC", "WS /{id}/rpc, /{id}/rpc/auth, /{id}/rpc/services", "kRPC frames only. Any other path is closed with the reason Only RPC paths are proxied.",
                  PX + "Application.kt:147", "client configured with the proxy base URL", "a server tunnel with that id is up"),
             flow("Instance list", "HTTP GET /instances, unauthenticated", "id and name of every connected server", PX + "Application.kt:73",
                  "instance picker")),

        edge("s-reverse-proxy", "proxy", "tunnel / WS", "optional",
             flow("Server tunnel", "WebSocket /proxy/server?id&name&key", "multiplexed ProxyMessage frames: NewClient, ClientFrame, ClientDisconnected, AssignedId",
                  S + "services/ReverseProxyService.kt:128", "ReverseProxyWorker, default cron 0 * * * *",
                  "PROXY_HOSTNAME, PROXY_CONTROL_PORT, PROXY_SSL, PROXY_ID, PROXY_NAME, PROXY_KEY"),
             flow("Keepalive", "protocol Ping every 10 s, Pong from the proxy", "liveness. The server closes after 30 s without any frame.",
                  S + "services/ReverseProxyService.kt:144")),
        edge("s-reverse-proxy", "ep-rpc-public", "in-process", "local",
             flow("Tunnelled public clients", "in-process KrpcServer over MultiplexedTransport", "NewClient frames for /rpc and /rpc/auth get the public services",
                  S + "services/ReverseProxyService.kt:216", "NewClient frame")),
        edge("s-reverse-proxy", "ep-rpc-auth", "in-process", "local",
             flow("Tunnelled authenticated clients", "in-process KrpcServer over MultiplexedTransport",
                  "NewClient frames for /rpc/services get the authenticated services after the forwarded Bearer token is validated",
                  S + "services/ReverseProxyService.kt:216", "NewClient frame")),
        edge("s-remote-mirror", "other-server", "kRPC / WS", "optional",
             flow("Mirror pull", "kRPC over WebSocket at /rpc/auth and /rpc/services, CBOR",
                  "stats, server paths, users with hashes, images, artists, aliases, albums, songs, playlists, likes, image bytes and audio in 64 KB chunks",
                  S + "services/RemoteMirrorService.kt:222", "admin start from the page or IRemoteMirrorService", "remote admin username and password"),
             flow("Setup from mirror at boot", "the same kRPC pull with isImport and importUsers", "a full import into an empty database, then halt with exit 0 for a restart",
                  S + "Application.kt:151", "startup with 0 songs and at most 1 user", "SETUP_FROM_MIRROR_URL, SETUP_FROM_MIRROR_USERNAME, SETUP_FROM_MIRROR_PASSWORD")),
        edge("s-remote-mirror", "proxy", "HTTP + WS", "optional",
             flow("Instance list for the mirror", "HTTP GET /instances", "ids of servers behind the proxy", S + "services/RemoteMirrorService.kt:211",
                  "mirror setup with useProxy"),
             flow("Mirror through the proxy", "kRPC over WebSocket at /{id}/rpc...", "the same mirror pull with /<id> added to the base URL",
                  S + "services/RemoteMirrorService.kt:862", "mirror with useProxy and proxyInstanceId")),
        edge("other-server", "ep-rpc-auth", "kRPC / WS", "optional",
             flow("This server as mirror source", "kRPC IMirrorService on /rpc/services", "entity flows, password hashes and getSongData, where quality -1 sends the original file",
                  S + "services/MirrorService.kt:133", "the other server starts a mirror", "an admin account on this server")),
        edge("ep-rpc-auth", "s-mirror-source", "in-process", "local",
             flow("Mirror source methods", "RPC adapter to MirrorService", "every IMirrorService method, all @RequiresAdmin", C + "services/IMirrorService.kt:43")),
        edge("ep-mirror-admin", "s-remote-mirror", "in-process", "local",
             flow("Mirror control", "route handlers calling RemoteMirrorService", "start, stop, reset, remote listings and the progress StateFlow",
                  S + "routing/Mirror.kt:658", "admin action")),
        edge("ep-mirror-admin", "redis", "RESP", "optional",
             flow("HTTP output cache", "Ktor SimpleCache through RedisCacheProvider", "GET /admin/mirror/remote-image/{imageId} cached 14 days. It is the only cacheOutput route. Without REDIS_HOST the cache is in memory.",
                  S + "routing/Mirror.kt:661", "admin page", "REDIS_HOST")),

        edge("ep-rpc-public", "s-auth", "in-process", "local",
             flow("Authenticate and refresh", "RpcAuthService to JwtService", "password check, session row, token pair", S + "services/RpcAuthService.kt:20")),
        edge("ep-auth-rest", "s-auth", "in-process", "local",
             flow("Token and session routes", "JwtService route handlers", "login, refresh, registration, session list and deactivation",
                  S + "services/JwtService.kt:130")),
        edge("ep-rpc-auth", "s-auth", "in-process", "local",
             flow("Bearer validation", "JWT provider synara-auth", "claims usr and ses, plus an active session check so deactivating a session revokes its tokens",
                  S + "services/JwtService.kt:84", "WebSocket upgrade")),
        edge("ep-radio", "s-auth", "in-process", "local",
             flow("API key check", "ApiKeyService", "key read from ?apiKey, X-API-Key or Bearer, scope radio", S + "core/Call.kt:54")),
        edge("ep-mcp", "s-auth", "in-process", "local",
             flow("API key check", "ApiKeyService", "scope mcp", S + "routing/McpRoutes.kt:97")),
        edge("ep-subsonic", "s-auth", "in-process", "local",
             flow("Subsonic authentication", "SubsonicAuthenticator", "apiKey with scope subsonic, or u+t+s with md5 of secret and salt, or u+p against the per-user secret",
                  S + "services/subsonic/SubsonicAuth.kt:23")),
        edge("ep-rpc-auth", "s-domain", "in-process", "local",
             flow("RPC adapters", "per-connection adapters delegating to Koin singletons", "each call runs through withAuthorization with the caller",
                  S + "routing/RpcRegistry.kt:184")),
        edge("ep-rest", "s-domain", "in-process", "local",
             flow("REST adapters", "generated register<Interface>Rest calls", "the same adapter constructions with client compat and authorization only",
                  S + "routing/RestRegistry.kt:40")),
        edge("ep-subsonic", "s-domain", "in-process", "local",
             flow("Direct service access", "SubsonicQueryService", "SongService, AlbumService and ArtistService injected directly, bypassing the RPC wrappers",
                  S + "services/subsonic/SubsonicRoutes.kt:128")),
        edge("ep-mcp", "s-domain", "in-process", "local",
             flow("Listen history queries", "ListenHistoryQueryService", "SongService, ArtistService, AlbumService and ScrobbleService",
                  S + "mcp/ListenHistoryQueryService.kt:51")),
        edge("ep-radio", "s-domain", "in-process", "local",
             flow("Radio sessions and transcoding", "RadioService, RadioChannelService, SongService, Transcoder", "the next songs and their AAC frames",
                  S + "routing/RadioRoutes.kt:35")),
        edge("ep-rpc-auth", "s-import", "in-process", "local",
             flow("Import requests", "IImportService.importUrls and importIds", "URLs, ISRCs and UPCs to import", S + "services/import/ImportService.kt:67",
                  "user action", "IMPORT capability")),
        edge("ep-rpc-auth", "s-credentials", "in-process", "local",
             flow("Credential management pages", "IUiService render and invoke on seven admin-only contributions",
                  "local credentials, the credential server connection, its clients, grants and credentials", UI + "CredentialServerUi.kt:189",
                  "admin user action", "user.isAdmin")),
        edge("s-domain", "s-db", "in-process", "local",
             flow("Transactions", "dbQuery, a suspendTransaction on Dispatchers.IO", "all reads and writes. EntityChangeRecorder stamps change rows in the same transaction.",
                  S + "core/db/DbQuery.kt:7")),
        edge("s-domain", "s-hue", "hook", "local",
             flow("Now playing hook", "HookService event NowPlayingChanged", "the song a session is playing", S + "services/hue/HueService.kt:143",
                  "ScrobbleService emits on now playing")),
        edge("s-domain", "s-recommendation", "hook", "local",
             flow("Dirty marking", "hooks ListenIngested and PlaylistChanged through RecommendationPlugin", "marks the training data dirty",
                  S + "services/recommendation/RecommendationPlugin.kt:21", "a listen is ingested or a playlist changes")),
        edge("s-plugins", "ep-subsonic", "in-process", "local",
             flow("Plugin routes", "IRoutePlugin mounted with a late application.routing block", "routes outside the JWT scope, each plugin does its own auth",
                  S + "plugins/PluginManager.kt:118", "plugin load")),
        edge("s-plugins", "s-import", "in-process", "local",
             flow("Importers and indexers", "registerIndexer and importer registration", "the Tidal, Gamdl, Youtube and Soundcloud importers and their indexers",
                  S + "plugins/PluginManager.kt:71", "plugin load")),
        edge("s-plugins", "s-credentials", "in-process", "local",
             flow("Plugin credentials", "context.credentials get, store and remove", "plugin:<id>:<name>. Remote when granted, else the local encrypted PluginSettingTable row. store and remove throw for remote-managed names.",
                  S + "services/credentials/PluginCredentialsFactory.kt:20", "plugin code")),

        edge("s-credentials", "cred-server", "REST", "optional",
             flow("Token exchange", "HTTP POST /token", "clientId and clientSecret, returns an ES256 JWT with expiresAt and the grant list",
                  S + "services/credentials/remote/CredentialServerClient.kt:81",
                  "connect, 60 s before expiry, one retry on 401, a 403, a local miss (at most once per 60 s), an admin mutation, UI test",
                  "CREDENTIAL_SERVER_URL, CREDENTIAL_SERVER_CLIENT_ID, CREDENTIAL_SERVER_CLIENT_SECRET, or the stored connection"),
             flow("Credential fetch", "HTTP GET /credentials/{name} with Bearer", "an access token, developer token, API key, key pair or files",
                  S + "services/credentials/remote/CredentialServerClient.kt:106", "on demand per consumer call, cached except for files",
                  "the name is in the grants"),
             flow("Auth file write-back", "HTTP PUT /credentials/{name}/files with Bearer", "changed auth.json, token.json or cookies with the expected fingerprint. A mismatch answers 409.",
                  S + "services/credentials/remote/CredentialServerClient.kt:119", "after an importer CLI run when a file changed", "write-back grant"),
             flow("Health", "HTTP GET /health", "ok, protocolVersion and jar version", S + "services/credentials/admin/CredentialServerAdminClient.kt:58",
                  "UI render and test, 5 s timeout"),
             flow("Client administration", "HTTP /admin/clients* with X-Admin-Key", "list, create, enable, grants, rotate secret, revoke tokens, delete",
                  S + "services/credentials/admin/CredentialServerAdminClient.kt:61", "admin UI actions, admin probe cached 30 s",
                  "CREDENTIAL_SERVER_ADMIN_KEY or the stored key"),
             flow("Credential administration", "HTTP /admin/credentials*, /admin/presets with X-Admin-Key", "upsert, delete, test and list",
                  S + "services/credentials/admin/CredentialServerAdminClient.kt:81", "admin UI actions", "admin key"),
             flow("Tidal device login relay", "POST /admin/credentials/{name}/tidal-login, GET /admin/tidal-logins/{id}/events as NDJSON, DELETE to cancel",
                  "device code, verification URL and state events relayed into the admin UI", S + "services/credentials/admin/CredentialServerAdminClient.kt:96",
                  "admin starts a Tidal login", "admin key"),
             flow("Use local login", "HTTP PUT /admin/credentials/{name}", "the server's own auth.json or token.json content",
                  UI + "CredentialServerCredentialContribution.kt:475", "admin action", "admin key and a local file"),
             flow("Register this server as a client", "HTTP POST /admin/clients with the grant list", "a new client with every existing core name granted, write-back only for Tidal sessions",
                  UI + "CredentialServerServerContribution.kt:319", "admin action", "admin key")),
        edge("s-credentials", "tidal-auth", "HTTPS", "optional",
             flow("Local client credentials exchange", "HTTPS POST /v1/oauth2/token with Basic auth", "the app token for the Tidal API, cached until 60 s before expiry",
                  S + "services/credentials/ClientCredentialsExchange.kt:72", "first API call in local mode", "TIDAL_CLIENT_ID and TIDAL_CLIENT_SECRET, or stored values")),
        edge("s-credentials", "spotify-accounts", "HTTPS", "optional",
             flow("Local client credentials exchange", "HTTPS POST /api/token, form style", "the app token for the Spotify API",
                  S + "services/credentials/LocalCredentialProvider.kt:94", "first API call in local mode", "Spotify client id and secret")),
        edge("s-credentials", "s-db", "in-process", "local",
             flow("Local credential store", "settings rows, AES-GCM", "admin-stored credentials under plugin id credentials and the stored credential server connection under credentialserver",
                  S + "services/credentials/LocalCredentialStore.kt:66")),
        edge("cred-server", "cred-db", "JDBC", "always",
             flow("Credential store", "JDBC, pool of 1 on SQLite with WAL, 10 on PostgreSQL", "clients, grants, signing keys and credentials encrypted with AES-256-GCM",
                  CS + "db/CredentialDatabase.kt:17", None, "CREDENTIAL_SERVER_DB_URL")),
        edge("cred-server", "tidal-auth", "HTTPS", "optional",
             flow("Client credentials for tidal.api", "HTTPS POST /v1/oauth2/token with Basic auth", "an app access token, cached in memory until expiry minus 60 s",
                  CS + "broker/OAuthClientCredentialsBroker.kt:37", "a fetch when the cache expired", "tidal.api stored"),
             flow("Session refresh on every hand-out", "HTTPS POST token with grant refresh_token", "a fresh Tidal session. The rotated refresh token is persisted centrally.",
                  CS + "broker/TidalAuthApi.kt:37", "every fetch or test of importer.tiddl or importer.tdn", "a stored session"),
             flow("Device login", "HTTPS POST device_authorization, then token polling", "loginId, verificationUri and userCode. A background coroutine polls at Tidal's interval until granted, expired or failed.",
                  CS + "broker/TidalDeviceLoginManager.kt:43", "admin starts a login")),
        edge("cred-server", "spotify-accounts", "HTTPS", "optional",
             flow("Client credentials for spotify.api", "HTTPS POST /api/token, form style", "an app access token, cached in memory",
                  CS + "broker/CredentialPresets.kt:14", "a fetch when the cache expired", "spotify.api stored")),
        edge("s-metadata", "s-credentials", "in-process", "local",
             flow("Provider credentials", "CredentialProvider.resolve", "tidal.api, spotify.api, applemusic.developer, acoustid.api, theaudiodb.api, linkresolver.api, imagecache.token",
                  S + "services/metadata/TidalService.kt:32", "before a provider call")),
        edge("s-tiddl", "s-credentials", "in-process", "local",
             flow("importer.tiddl materialised", "ImporterCredentialMaterializer.withFiles", "per-name mutex, fetch, write ~/.tiddl/auth.json with mode 0600, run, diff, write back. Without a remote grant the command runs on the local file.",
                  S + "services/import/TiddlService.kt:43", "every tiddl command while importer.tiddl is managed remotely")),
        edge("s-tdn", "s-credentials", "in-process", "local",
             flow("importer.tdn materialised", "ImporterCredentialMaterializer.withFiles", "~/.config/tidal_dl_ng/token.json written before the run and written back when it changed",
                  S + "services/import/TdnService.kt:118", "every tdn command while importer.tdn is managed remotely")),
        edge("s-gamdl", "s-credentials", "in-process", "local",
             flow("importer.gamdl materialised", "ImporterCredentialMaterializer.withFiles", "cookies file and optional Widevine device file at the configured paths",
                  S + "services/gamdl/GamdlService.kt:92", "every gamdl command while importer.gamdl is managed remotely")),
        edge("s-ytdlp", "s-credentials", "in-process", "local",
             flow("youtube.api key", "CredentialProvider.resolve", "the YouTube Data API key. The yt-dlp importers themselves declare no credential.",
                  S + "services/youtube/YoutubeApiService.kt:97", "YouTube metadata lookup")),
        edge("s-podcasts", "s-credentials", "in-process", "local",
             flow("podcastindex.api pair", "CredentialProvider.resolve", "key and secret for the Podcast Index auth headers",
                  S + "services/podcast/index/PodcastIndexOrgIndex.kt:59", "podcast search")),

        edge("s-import", "s-metadata", "in-process", "local",
             flow("Code and URL resolution", "ImporterProxy to LinkResolverService", "a URL, ISRC or UPC turned into an importable platform URL",
                  S + "services/import/ImporterProxy.kt:50", "user import"),
             flow("Upcoming release lookup", "UpcomingReleaseImportService", "Apple catalog tracklist, then each ISRC looked up on Tidal and queued as a tidal.com track URL",
                  S + "services/import/UpcomingReleaseImportService.kt:87", "intake of a release that is not out yet"),
             flow("Import search", "ImportService.search", "Tidal search results for the import page", S + "services/import/ImportService.kt:642", "user search")),
        edge("s-import", "s-musicbrainz", "in-process", "local",
             flow("Sibling provider URLs", "MusicBrainzCacheService", "URLs of the same release on other providers from mb_relation_provider",
                  S + "services/metadata/MusicBrainzCacheService.kt:569", "importer choice")),
        edge("s-import", "s-tidal-importer", "in-process", "local",
             flow("Run an import job", "JobService to importerProxy.importContent", "the queued entry, one running job per kind", S + "services/import/ImportService.kt:473",
                  "queue")),
        edge("s-import", "s-gamdl", "in-process", "local",
             flow("Apple Music import", "importerProxy.importContent", "Apple Music URLs", S + "services/import/ImporterProxy.kt:116", "Apple URL import")),
        edge("s-import", "s-ytdlp", "in-process", "local",
             flow("YouTube and SoundCloud import", "importerProxy.importContent", "YouTube and SoundCloud URLs", S + "services/import/ImporterProxy.kt:116",
                  "YouTube or SoundCloud URL import")),
        edge("s-import", "s-tidal-sync", "in-process", "local",
             flow("Favourites sync", "ImportService.syncFavourites", "liked songs newer than the last favSync row, imported through the Tidal importer",
                  S + "services/import/ImportService.kt:567", "user action on the importer page")),
        edge("s-import", "music-dir", "files", "local",
             flow("Collect imported files", "BaseImporter.collectImportedFiles", "files modified since the start of the run, Atmos .m4a converted to lossless, .m3u playlists parsed",
                  S + "services/import/BaseImporter.kt:81", "after the download tool exits")),
        edge("s-tidal-importer", "s-metadata", "in-process", "local",
             flow("Tidal metadata before download", "TidalService at HIGH priority", "track and album metadata and cover URLs",
                  S + "services/import/TidalBaseImporter.kt:158", "import job")),
        edge("s-tidal-importer", "s-musicbrainz", "in-process", "local",
             flow("MusicBrainz match", "release by barcode or title, or a recording search", "canonical tags and MBIDs",
                  S + "services/import/TidalBaseImporter.kt:190", "import job")),
        edge("s-tidal-importer", "caa", "HTTPS", "always",
             flow("Import cover", "HTTPS GET front cover", "the cover when none was provided, before falling back to Tidal", S + "services/import/TidalBaseImporter.kt:316",
                  "import job")),
        edge("s-tidal-importer", "tidal-api", "HTTPS", "optional",
             flow("Cover and animated cover download", "HTTPS GET from the Tidal image hosts", "the cover and the animated cover, stored and linked to song and album",
                  S + "services/import/TidalBaseImporter.kt:337", "import job")),
        edge("s-tidal-importer", "s-tiddl", "in-process", "local",
             flow("Download with tiddl", "collectImportedFiles", "the URLs to download", S + "services/import/TiddlService.kt:23", "import job, default importer")),
        edge("s-tidal-importer", "s-tdn", "in-process", "local",
             flow("Download with tidal-dl-ng", "collectImportedFiles", "the URLs to download", S + "services/import/TdnService.kt:35", "import job with tdn selected")),
        edge("s-tiddl", "tiddl", "subprocess", "local",
             flow("tiddl commands", "python3 -u tiddl download url <urls>, download fav --types, auth login --no-browser", "audio files. Login is capped at 3 min, the authorized check at 10 s.",
                  S + "services/import/TiddlService.kt:22", "import job", "~/.tiddl/auth.json")),
        edge("s-tdn", "tdn", "subprocess", "local",
             flow("tdn commands", "python3 -u tdn dl <urls>, dl_fav <type>, login", "audio files and .m3u playlists", S + "services/import/TdnService.kt:34",
                  "import job", "~/.config/tidal_dl_ng/token.json")),
        edge("s-gamdl", "gamdl", "subprocess", "local",
             flow("gamdl download", "gamdl --no-config-file --cookies-path --output-path --template-folder-album --template-file-single-disc [--wvd-path] [--codec-song] <urls>",
                  "Apple Music .m4a files", S + "services/gamdl/GamdlService.kt:77", "Apple URL import", "cookies file, optional .wvd file")),
        edge("s-gamdl", "ffmpeg", "subprocess", "local",
             flow("Transcode to lossless", "ffmpeg -y -i in.m4a -map 0:a -map 0:v? -c:a flac -c:v copy -map_metadata 0 out", "each new .m4a, with WAV and AIFF variants by AUDIO_LOSSLESS_FORMAT",
                  S + "services/gamdl/GamdlService.kt:307", "after a gamdl download")),
        edge("s-ytdlp", "ytdlp", "subprocess", "local",
             flow("yt-dlp download", "yt-dlp -x --audio-format <flac|wav|aiff> --convert-thumbnails jpg --write-subs --convert-subs lrc --add-metadata",
                  "audio, thumbnail and subtitles. SoundCloud uses the same command without subtitles.", S + "services/youtube/YoutubeService.kt:58",
                  "YouTube or SoundCloud URL import", "optional YTDLP_CONFIG_PATH"),
             flow("yt-dlp probes", "yt-dlp -J --flat-playlist and -J --simulate", "video and playlist metadata when no API key is set",
                  S + "services/youtube/YoutubeService.kt:228", "import without YOUTUBE_API_KEY")),
        edge("ytdlp", "pot-provider", "HTTP", "optional",
             flow("PO token provider", "assumed from the compose file through the yt-dlp configuration", "proof-of-origin tokens for YouTube",
                  "docker-compose.server.yml:77", None, "docker-compose.server.yml only")),
        edge("s-ytdlp", "youtube-api", "HTTPS", "optional",
             flow("YouTube metadata", "HTTPS GET videos, playlistItems, playlists with &key=", "video and playlist metadata",
                  S + "services/youtube/YoutubeApiService.kt:148", "YouTube import", "YOUTUBE_API_KEY or youtube.api")),
        edge("s-ytdlp", "youtube-music", "HTTPS", "always",
             flow("Square cover scrape", "queued HTTPS GET of music.youtube.com/watch?v={id} at LOW priority", "the og:image URL when the API thumbnail is not square", S + "services/youtube/YoutubeApiService.kt:132",
                  "YouTube import")),
        edge("s-ytdlp", "caa", "HTTPS", "always",
             flow("Cover for matched imports", "HTTPS GET front cover", "the cover of the matched MusicBrainz release", S + "services/youtube/YoutubeService.kt:347",
                  "YouTube or SoundCloud import with a MusicBrainz match")),
        edge("s-tidal-sync", "tidal-login", "browser redirect", "optional",
             flow("Per-user login", "authorize URL with a PKCE challenge, returned by IImportService.getAuthUrl", "the user signs in at Tidal in a browser",
                  S + "services/sync/TidalSyncServiceBase.kt:35", "user links Tidal", "TIDAL_CLIENT_ID")),
        edge("s-tidal-sync", "tidal-auth", "HTTPS", "optional",
             flow("User token and refresh", "HTTPS POST token with code_verifier, then refresh_token", "per-user tokens stored in syncService",
                  S + "services/sync/TidalSyncServiceBase.kt:75", "login and token expiry")),
        edge("s-tidal-sync", "tidal-api", "HTTPS", "optional",
             flow("Pull liked tracks", "HTTPS GET /users/me and /userCollections/{id}/relationships/tracks?include=tracks&sort=-tracks.addedAt",
                  "pulls the liked tracks, cursor-paged, with a 10 s wait on 429", S + "services/sync/TidalSyncService.kt:81",
                  "user starts a favourites sync", "per-user OAuth token")),

        edge("s-metadata", "s-http-queue", "in-process", "local",
             flow("Queued provider GETs", "HttpClientQueueService.enqueue", "the GETs made through ApiClient.queueInstance, paced per host", S + "core/HttpClient.kt:131")),
        edge("s-metadata", "tidal-api", "HTTPS", "optional",
             flow("Tidal catalogue", "HTTPS GET searchResults, /tracks, /albums, /artists, /playlists and their relationships",
                  "track, album, artist and playlist metadata. The user's OAuth token is preferred over the app token when a user is present.",
                  S + "services/metadata/TidalService.kt:109", "import job, release linking, ISRC enrichment, artist images, import search",
                  "tidal.api or a linked user token")),
        edge("s-metadata", "redis", "RESP", "optional",
             flow("Tidal metadata cache", "Jedis cluster GET and SET", "tidal_track::, tidal_album::, tidal_artist::, tidal_playlist:: objects for 30 days",
                  S + "core/TidalService.kt:10", "per Tidal lookup", "REDIS_HOST")),
        edge("s-metadata", "itunes", "HTTPS", "always",
             flow("iTunes search and lookup", "HTTPS GET /search and /lookup", "song, artist and album search, and lookup by isrc, upc or id",
                  S + "services/metadata/AppleMusicService.kt:142", "release linking, enrichment")),
        edge("s-metadata", "apple-catalog", "HTTPS", "optional",
             flow("Apple Music catalog", "HTTPS GET songs?filter[isrc], albums?filter[upc], albums/{id}, albums/{id}/tracks, artists/{id}/albums with a Bearer developer token",
                  "catalog songs, albums and artist albums", S + "services/metadata/AppleMusicService.kt:95", "ISRC enrichment, release feed, upcoming releases",
                  "applemusic.developer")),
        edge("s-metadata", "spotify-api", "HTTPS", "optional",
             flow("Spotify search", "HTTPS GET /v1/search for track, isrc:, upc:, artist and album", "provider ids and artist images",
                  S + "services/metadata/SpotifyService.kt:27", "ISRC enrichment, artist images", "spotify.api")),
        edge("s-metadata", "deezer", "HTTPS", "always",
             flow("Deezer lookups", "HTTPS GET /search/artist, /track/isrc:{isrc}, /album/upc:{upc}", "provider ids and artist images",
                  S + "services/metadata/DeezerService.kt:22", "ISRC enrichment, artist images")),
        edge("s-metadata", "audiodb", "HTTPS", "always",
             flow("Genres, biographies and images", "HTTPS GET search.php, artist-mb.php, album-mb.php, track-mb.php with the key in the path",
                  "metadata for entities that have MBIDs", S + "services/metadata/TheAudioDBService.kt:95",
                  "worker chain GenreMetadataWorker, ArtistImageWorker, MetadataTheAudioDBWorker", "theaudiodb.api, default key 123")),
        edge("s-metadata", "fpcalc", "subprocess", "local",
             flow("Fingerprint", "fpcalc -json <path>", "duration and Chromaprint fingerprint", S + "services/metadata/AcoustIdFingerprintService.kt:41",
                  "SongService.fetchMusicBrainzId for a song without an MBID")),
        edge("s-metadata", "acoustid", "HTTPS", "optional",
             flow("Fingerprint lookup", "HTTPS GET /v2/lookup with client, meta=recordings releasegroups, duration, fingerprint",
                  "recording MBIDs. Negative results are rechecked after 30 days and stored in song_acoustid.", S + "services/metadata/AcoustIdService.kt:191",
                  "MusicBrainzWorker 0 0 * * * or an RPC, before the MusicBrainz text search", "ACOUSTID_API_KEY or acoustid.api")),
        edge("s-metadata", "linkresolver", "HTTPS", "optional",
             flow("Link resolution", "HTTPS GET /resolve?url|isrc|upc and /supported with X-API-Key", "platform URLs for a release. /supported is cached 24 h and refreshed at startup.",
                  S + "services/metadata/LinkResolverService.kt:129", "import, enrichProviders for songs and albums, release processing",
                  "LINKRESOLVER_API_KEY or linkresolver.api")),
        edge("s-metadata", "image-cache", "HTTPS", "optional",
             flow("Publish an image", "HTTPS HEAD {IMAGE_CACHE_URL}/{imageHash}, then PUT with a Bearer token on 404", "image bytes, returning the public URL",
                  S + "services/metadata/ImageCacheService.kt:56", "getImageUrlByImageId", "IMAGE_CACHE_URL and IMAGE_CACHE_TOKEN or imagecache.token")),
        edge("s-musicbrainz", "s-http-queue", "in-process", "local",
             flow("Queued MusicBrainz GETs", "HttpClientQueueService.enqueue", "one request per second, 3 attempts on 503, 429 and 5xx",
                  S + "services/metadata/MusicBrainzService.kt:68")),
        edge("s-musicbrainz", "musicbrainz", "HTTPS", "always",
             flow("MusicBrainz web service", "HTTPS GET /recording, /release, /release-group, /artist, /url with User-Agent Synara/<version>",
                  "searches, ISRC and barcode lookups, browse by artist and release group, URL relations", S + "services/metadata/MusicBrainzService.kt:108",
                  "import job, MusicBrainzWorker 0 0 * * *, release feed, RPC"),
             flow("Mirror refresh", "the same endpoints at LOW priority", "rows older than 90 days, recordings referenced by listens",
                  S + "services/schedule/MusicBrainzCacheWorker.kt:104", "MusicBrainzCacheWorker after MusicBrainzWorker")),
        edge("s-musicbrainz", "caa", "HTTPS", "always",
             flow("Release group covers", "HTTPS GET /release-group/{id}/front", "covers for listened release groups into mb_release_group_cover",
                  S + "services/schedule/MusicBrainzCacheWorker.kt:219", "MusicBrainzCacheWorker")),
        edge("s-musicbrainz", "s-db", "in-process", "local",
             flow("MusicBrainz mirror tables", "read-through cache", "mb_artist, mb_recording, mb_release, mb_release_group, credits, ISRCs, mb_relation, mb_relation_provider",
                  S + "services/metadata/MusicBrainzCacheService.kt:88")),
        edge("s-releases", "s-musicbrainz", "in-process", "local",
             flow("Release feed lookups", "ReleaseService.fetchNewReleases", "releases by artist, release groups, releases and recordings per group",
                  S + "services/ReleaseService.kt:1115", "RecentReleaseWorker 0 1 * * * at LOW priority, refresh of one release at HIGH priority")),
        edge("s-releases", "s-metadata", "in-process", "local",
             flow("Provider links", "LinkResolver over URL relations, then Apple and Tidal album search when no link exists", "links stored through ProviderLinkService",
                  S + "services/ReleaseService.kt:1297", "RecentReleaseWorker, ProviderEnrichmentWorker after it"),
             flow("Apple Music releases of followed artists", "AppleMusicArtistResolver, then getArtistCatalogAlbums", "provider_release rows for a window of 180 days back and 365 days ahead",
                  S + "services/release/AppleMusicReleaseService.kt:314", "AppleMusicReleaseWorker 0 6 * * *", "applemusic.developer")),
        edge("s-releases", "caa", "HTTPS", "always",
             flow("Release feed covers", "HTTPS GET front cover", "covers for release feed entries", S + "services/ReleaseService.kt:1537", "release feed")),
        edge("s-releases", "mzstatic", "HTTPS", "optional",
             flow("Apple artwork", "HTTPS GET, outside the queue", "artwork for Apple Music releases", S + "services/release/AppleMusicReleaseService.kt:869",
                  "Apple Music release fetch")),
        edge("s-releases", "redis", "RESP", "optional",
             flow("Release image cache", "Jedis cluster GET and SET", "releaseImage:{releaseId}:{size} without TTL and releaseImage:{id}:missing for 1 h",
                  S + "services/ReleaseService.kt:1582", "release image request", "REDIS_HOST")),
        edge("s-lyrics", "lrclib", "HTTPS", "always",
             flow("LRCLIB lookup", "HTTPS GET /api/get with artist_name, track_name, album_name, duration", "pulls lyrics, synced preferred over plain",
                  S + "services/LrcLibService.kt:13", "LrcLibWorker 30 4 * * *")),
        edge("s-lyrics", "transcriber", "HTTP", "optional",
             flow("Transcribe and align", "HTTP POST /transcribe with path, artist, title and optional lyrics, GET /health",
                  "word and character timings stored as CBOR in synced_lyrics with provider whisperx_v1", S + "services/LyricsService.kt:86",
                  "LyricsSyncWorker 0 4 * * * (disabled by default) or the transcribeLyrics RPC, 15 min timeout", "TRANSCRIBER_URL, default http://localhost:8000")),
        edge("s-lyrics", "syncedlyrics", "subprocess", "local",
             flow("Lyrics search", "python3 -u -m syncedlyrics -v -o <tmp.lrc> [--synced-only] \"<title> - <artist>\"", "an .lrc file",
                  S + "services/LyricsSearch.kt:18", "lyrics search RPC, fallback inside transcribeLyrics")),
        edge("s-audio", "essentia", "subprocess", "local",
             flow("Audio features", "essentia_streaming_extractor_music writing a temp essentia_*.json", "features stored in song_audio_data",
                  S + "services/AudioAnalysisService.kt:285", "AudioAnalysisWorker 0 3 * * *", "binary on PATH")),
        edge("s-audio", "ffmpeg", "subprocess", "local",
             flow("PCM analysis", "ffprobe -show_entries and ffmpeg -v error -i f -map 0:a:0 -f md5 -", "stream info and the audio MD5 into pcm_info",
                  S + "services/PcmAnalysisService.kt:79", "PcmAnalysisWorker 20 5 * * *")),
        edge("s-audio", "metaflac", "subprocess", "local",
             flow("FLAC analysis and repair", "metaflac --list <file>, and --add-seekpoint=2s --add-padding=8192 <file> as a fix", "stream info into flac_info",
                  S + "services/FlacAnalysisService.kt:87", "FlacAnalysisWorker 0 5 * * *")),
        edge("s-audio", "music-dir", "files", "local",
             flow("Transcodes", "in-process JavaCV encoder", "Opus and AAC files under AUDIO_TRANSCODE_PATH", S + "audio/Transcoder.kt:71",
                  "AutoTranscodeWorker 0 3 * * *, downloads on demand")),
        edge("s-embeddings", "audio-embed", "HTTP", "optional",
             flow("Embed a batch", "HTTP POST /embed with 16 file paths", "one vector per path, stored in song_audio_embedding. A batch answered with another status than 200 stores nothing and its songs stay unembedded for the next run.",
                  S + "services/AudioEmbeddingService.kt:54", "AudioEmbeddingWorker after audio-analysis, 15 min timeout", "AUDIO_EMBED_URL")),
        edge("s-embeddings", "s-recommendation", "in-process", "local",
             flow("Dirty marking", "RecommendationService.markDirty", "new audio vectors make the next training run necessary",
                  S + "services/schedule/AudioEmbeddingWorker.kt:31", "after vectors were stored")),
        edge("audio-embed", "music-dir", "shared mount", "local",
             flow("Read audio", "read-only bind mount at the same path as the server", "audio files named in the request", "docker-compose.yml:105",
                  "per request")),
        edge("transcriber", "music-dir", "shared mount", "local",
             flow("Read audio", "bind mount at the same path as the server", "audio files named in the request", "docker-compose.yml:94", "per request")),
        edge("s-recommendation", "recsys-volume", "files", "local",
             flow("Training request", "files songs.jsonl, sequences.jsonl, meta.json, then request.ready",
                  "song ids with audio vectors and genres, and id sequences from user playlists, playlists, albums and listen sessions split at a 30 min gap",
                  S + "services/RecommendationService.kt:52", "RecommendationTrainWorker 0 7 * * *, only when dirty", "RECSYS_DATA_DIR"),
             flow("Result pickup", "2 s poll for result.ready or result.failed, then embeddings.jsonl", "64-dimensional vectors, cluster and mood, upserted into song_embedding in batches of 1000",
                  S + "services/RecommendationService.kt:254", "after a request, 5 min pickup timeout, 6 h result timeout")),
        edge("recsys", "recsys-volume", "files", "local",
             flow("Train and answer", "5 s poll for request.ready, writes embeddings.jsonl and result.ready or result.failed", "Word2Vec skip-gram, Ridge for cold songs, MiniBatchKMeans moods",
                  "recsys/main.py:124", "request.ready appears")),
        edge("s-podcasts", "podcast-hosts", "HTTPS", "always",
             flow("Feed refresh", "conditional HTTPS GET with ETag and Last-Modified on the podcast-feed client", "pulls RSS and artwork",
                  S + "services/podcast/PodcastFeedService.kt:50", "PodcastRefreshWorker 15 * * * *, subscribe RPC"),
             flow("Episode import", "HTTPS GET of the enclosure on the podcast-media client, 2 concurrent", "episode audio, probed after download",
                  S + "services/podcast/PodcastImportService.kt:83", "PodcastImportWorker */15 * * * *, importEpisode RPC"),
             flow("Stream proxy", "HTTPS GET with Range to the publisher host", "audio of episodes that are not imported", S + "services/podcast/PodcastStreamService.kt:65",
                  "playback"),
             flow("Transcripts", "lazy HTTPS GET, size-capped", "transcript files named by the feed", S + "services/podcast/PodcastService.kt:462", "getTranscript")),
        edge("s-podcasts", "podcast-index", "HTTPS", "optional",
             flow("Directory search", "HTTPS GET /api/1.0/search/byterm with X-Auth-Key, X-Auth-Date and Authorization = sha1(key + secret + date)", "podcast search results",
                  S + "services/podcast/index/PodcastIndexOrgIndex.kt:62", "searchIndex RPC", "podcastindex.api")),
        edge("s-hue", "hue-bridge", "HTTPS + DTLS", "optional",
             flow("Pairing", "HTTPS GET /api/0/config and POST /api with the link button", "username and clientkey stored in hue_bridge",
                  S + "services/hue/HueBridgeClient.kt:72", "startPairing RPC"),
             flow("CLIP v2 commands", "HTTPS GET and PUT /clip/v2/resource/{light|room|zone|grouped_light|scene|entertainment_configuration} with hue-application-key",
                  "light state, with light commands capped at 8 per second", S + "services/hue/HueBridgeClient.kt:119", "NowPlayingChanged hook", "a paired bridge"),
             flow("Entertainment stream", "DTLS 1.2 PSK over UDP port 2100, HueStream frames every 40 ms", "per-light colours at 25 frames per second",
                  S + "services/hue/HueEntertainmentStream.kt:135", "after a PUT on entertainment_configuration starts streaming", "application key and clientkey")),
        edge("s-hue", "hue-cloud", "HTTPS", "optional",
             flow("Cloud discovery", "HTTPS GET https://discovery.meethue.com/", "bridge addresses, merged with the mDNS results on every discovery", S + "services/hue/HueDiscoveryService.kt:87",
                  "discover RPC")),
        edge("s-hue", "mdns", "mDNS", "optional",
             flow("Bridge discovery", "direct mDNS query for _hue._tcp.local. through MdnsQuery, plus a browse on the shared JmDNS instance", "bridge addresses", S + "services/hue/HueDiscoveryService.kt:63",
                  "discover RPC")),
        edge("s-jmdns", "mdns", "mDNS", "always",
             flow("Service advertisement", "mDNS registration of synara-api as _synara-api._tcp.local.", "host and port, no TXT properties",
                  S + "Application.kt:99", "ApplicationStarted, unregistered on stop")),
        edge("s-listenbrainz", "listenbrainz", "HTTPS", "optional",
             flow("Pull listens", "HTTPS GET /1/user/{name}/listens?count=1000 with an optional Token header", "pulls listen history, 4 attempts with linear backoff",
                  S + "services/sync/ListenBrainzService.kt:243", "ListenBrainzSyncWorker 0 * * * *, link and syncNow", "per-user link rows"),
             flow("Submit a manual mapping", "HTTPS POST /1/metadata/submit_manual_mapping with the user's token", "an MSID to MBID mapping. It is the only POST in ListenBrainzService.",
                  S + "services/sync/ListenBrainzService.kt:320", "user action")),
        edge("s-listen-backup", "listen-backup", "REST", "optional",
             flow("Send listens", "HTTP POST /listens with X-Backup-Key", "batches of LOCAL listens with the serverId, default 1000 per batch. The cursor is persisted after each acknowledged batch.",
                  S + "services/sync/ListenBackupService.kt:220", "ListenBackupWorker 30 * * * *, syncNow", "row listen_backup_config with enabled and url"),
             flow("Test connection", "HTTP GET /health and /status?serverId=", "health and the remote listen count", S + "services/sync/ListenBackupService.kt:195",
                  "admin testConnection")),
        edge("listen-backup", "backup-db", "JDBC", "always",
             flow("Store listens", "JDBC, pool of 1 on SQLite with WAL, 10 on PostgreSQL", "rows in backup_listen, receivedAt stamped by the receiver", LB + "ListenBackupStore.kt:70",
                  None, "DB_URL of the receiver")),
        edge("s-search", "s-db", "in-process", "local",
             flow("Search queue", "triggers fill search_index_queue, a loop rebuilds the tsvector columns and deletes the queue rows", "search text with weights A to D",
                  S + "services/SearchIndexWorker.kt:26", "continuous, 2 s idle poll", "PostgreSQL only")),
        edge("s-search", "redis", "RESP", "optional",
             flow("RediSearch", "FT.CREATE at startup, HSET from the worker, DEL on delete and merge hooks, FT.SEARCH on search requests",
                  "song, artist and album documents under the prefix synara. Empty results or errors fall back to database search.", S + "services/RedisSearchService.kt:21",
                  "startup, SearchIndexWorker, search requests", "REDIS_USE_SEARCH=true and PostgreSQL")),
        edge("s-images", "redis", "RESP", "optional",
             flow("Image blob cache", "Jedis cluster GET and SET", "image:{id}:{size} bytes without TTL, and animated:{id} when REDIS_CACHE_ANIMATED_IMAGES is true",
                  S + "services/ImageService.kt:209", "image request", "REDIS_HOST")),
        edge("s-images", "s-http-queue", "in-process", "local",
             flow("Re-download lost image bytes", "queued HTTPS GET of the stored origin URL at LOW priority", "the original image from its source host",
                  S + "services/ImageService.kt:646", "ImageAnalysisWorker, when the image file is missing or unreadable")),
        edge("s-backup", "backup-dir", "files", "local",
             flow("Database backup", "backup-{timestamp}.zip with schema.version, database.cbor.zst, files.tree.cbor.zst, images.index.cbor.zst, plus blobs/",
                  "a full dump without search vectors, plus the audio inventory and image blobs", S + "services/BackupService.kt:150", "DatabaseBackupWorker 0 2 * * *, createBackup RPC", "BACKUP_DIR"),
             flow("User playlist backup", "playlists-{userId}-{timestamp}.json under user-playlists/", "one JSON file per user", S + "services/UserPlaylistBackupService.kt:46",
                  "UserPlaylistBackupWorker 0 2 * * *"),
             flow("Restore", "reads a zip, clears and refills all tables in one transaction, copies missing images back from blobs", "a full restore, refused when the dump is below base or newer than the server",
                  S + "services/BackupService.kt:339", "loadBackup RPC, or startup with an empty database", "SETUP_FROM_BACKUP")),
        edge("s-backup", "s-db", "in-process", "local",
             flow("Export and import", "DbManagementService", "per-table CBOR rows in a zstd stream, change tracking restarted after an import", S + "services/DbManagementService.kt:111")),
        edge("s-db", "db", "JDBC", "always",
             flow("All state", "JDBC through HikariCP", "every table of the schema", S + "services/DatabaseManager.kt:49", "startup and runtime",
                  "DB_DRIVER, DB_URL, DB_USER, DB_PASSWORD"),
             flow("Migrations", "MigrationBaseCheck, then Flyway from db/migrations/{postgres|sqlite}", "schema changes. A refusal halts the JVM with exit 1.",
                  S + "services/DatabaseManager.kt:91", "startup")),
    ]


def notes():
    return [
        {"title": "ReverseProxyWorker is the only caller that starts the tunnel",
         "text": "ReverseProxyService.startService is called from ReverseProxyWorker, which has cron 0 * * * *. No other caller exists in the server sources, and configureServices does not start it.",
         "src": S + "services/schedule/ReverseProxyWorker.kt:23"},
        {"title": "Proxied calls run on a ProxyCall",
         "text": "For clients behind the proxy the server builds a ProxyCall. Its request.cookies throws UnsupportedOperationException and every address field is 127.0.0.1, so a session created through the proxy records that address.",
         "src": S + "services/ReverseProxyService.kt:298"},
        {"title": "Only the server side of the proxy checks a key",
         "text": "GET /instances and the client WebSocket /{id}/... take no key. /proxy/server compares the key query parameter or the X-Proxy-Key header only when proxy.key (PROXY_KEY) is set.",
         "src": PX + "Application.kt:73"},
        {"title": "The mirror admin page is served before the JWT block",
         "text": "GET /admin/mirror returns the HTML page with its own login form. The control routes under it sit inside authenticate(JwtService.AUTH_PROVIDER).",
         "src": S + "routing/Mirror.kt:88"},
        {"title": "Server stats are a public service",
         "text": "IServerStatsService is one of the three public services. getStats includes the version, the commit hash, the OS name and the kernel version.",
         "src": S + "services/ServerStatsService.kt:119"},
        {"title": "The refresh token is stored as issued",
         "text": "JwtService passes the generated refresh token to RefreshTokenService.createToken, which writes it into the column tokenHash and looks it up by equality.",
         "src": S + "services/RefreshTokenService.kt:81"},
        {"title": "The Redis entrypoint removes its node data on start",
         "text": "redis-cluster/entrypoint.sh runs rm -f /data/nodes.conf and rm -rf /data/node-* before it starts the instances.",
         "src": "redis-cluster/entrypoint.sh:18"},
        {"title": "No compose file sets REDIS_USE_SEARCH",
         "text": "redis.useSearch defaults to false and none of the docker-compose files or truenas-custom-app.yml sets REDIS_USE_SEARCH, so in those setups Redis is used as a cache and search runs on the database.",
         "src": "server/src/main/resources/application.yaml:23"},
        {"title": "No method carries @Cached",
         "text": "withCaching is part of the RPC wrapper chain, but no method in server, common-rpc or plugin-api is annotated with @Cached, so the rpc_cache: key space stays empty.",
         "src": S + "utils/Caching.kt:49"},
        {"title": "The two server images install different tools",
         "text": "Dockerfile installs tidal-dl-ng, syncedlyrics, tiddl, ffmpeg and fpcalc. Dockerfile.nobuild installs syncedlyrics, yt-dlp, tiddl, ffmpeg, flac, libchromaprint-tools, deno and the Essentia extractor. Neither installs gamdl.",
         "src": "Dockerfile.nobuild:79"},
        {"title": "Calls made with ApiClient.instance are not paced by the queue",
         "text": "The per-host queue covers calls made through ApiClient.queueInstance. Apple artwork, the release feed cover download, the image cache HEAD and PUT, the transcriber, audio-embed, the Tidal user token POSTs and the ListenBrainz mapping POST use ApiClient.instance directly.",
         "src": S + "services/release/AppleMusicReleaseService.kt:869"},
        {"title": "OdesliService has no references",
         "text": "The class exists, but nothing in the server sources refers to it, so it has no node or arrow here.",
         "src": S + "services/metadata/OdesliService.kt:12"},
        {"title": "pot-provider appears only in a compose file",
         "text": "The container is defined in docker-compose.server.yml and no Kotlin source or Dockerfile mentions it. The arrow from yt-dlp is an assumption.",
         "src": "docker-compose.server.yml:77", "flags": ["unverified"]},
        {"title": "No route was found for the Tidal login redirect",
         "text": "IImportService.getAuthUrl builds the authorize URL with the redirect path /sync/tidal/callback. The server sources contain no route with that path and no caller of SyncService.handleAuth or handleCallback. How the redirect is completed was not established.",
         "src": S + "services/sync/SyncService.kt:44", "flags": ["unverified"]},
        {"title": "One admin key covers the whole credential server",
         "text": "CredentialServerAdminClient sends a single X-Admin-Key. A Synara server configured with it can list and change every client, grant and credential on that credential server, and its admin pages are open to users with isAdmin.",
         "src": S + "services/credentials/admin/CredentialServerAdminClient.kt:61"},
        {"title": "TRANSCRIBER_URL has a default",
         "text": "transcriber.url defaults to http://localhost:8000. docker-compose.server.yml defines no transcriber service.",
         "src": "server/src/main/resources/application.yaml:54"},
        {"title": "docs/ARCHITECTURE.md differs from the code in three places",
         "text": "It describes all three sidecars as reached over HTTP and names MetadataFetchingService for the transcriber, while recsys exchanges files and the transcriber is called from LyricsService. It lists withCaching as the outermost RPC wrapper, while RpcRegistry.wrap applies withClientCompat last. It mentions a pluginModule that Application.kt does not define.",
         "src": "docs/ARCHITECTURE.md:19"},
    ]


def build(root):
    return {
        "id": "system",
        "tab": "System",
        "noun": "component",
        "blurb": "Every process, server subsystem, datastore, tool and external service, and which one opens each link. Arrows point from the side that starts the call, and a click on a line lists every flow it carries.",
        "out": "Connects to",
        "inn": "Connected from",
        "layout": {"kind": "columns"},
        "groups": GROUPS,
        "styles": STYLES,
        "nodes": nodes(),
        "edges": edges(),
        "notes": notes(),
    }
